// <copyright file="BackupBucket.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace OpenApiSpecForClickHouseCloud.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<BackupBucket>),
        new System.Type[] {
            typeof(AwsBackupBucketPropertiesCase),
            typeof(GcpBackupBucketPropertiesCase),
            typeof(AzureBackupBucketPropertiesCase)
        },
        true
    )]
    public abstract class BackupBucket
    {
        /// <summary>
        /// This is AwsBackupBucketProperties case.
        /// </summary>
        /// <returns>
        /// The BackupBucket instance, wrapping the provided AwsBackupBucketProperties value.
        /// </returns>
        public static BackupBucket FromAwsBackupBucketProperties(AwsBackupBucketProperties awsBackupBucketProperties)
        {
            return new AwsBackupBucketPropertiesCase().Set(awsBackupBucketProperties);
        }

        /// <summary>
        /// This is GcpBackupBucketProperties case.
        /// </summary>
        /// <returns>
        /// The BackupBucket instance, wrapping the provided GcpBackupBucketProperties value.
        /// </returns>
        public static BackupBucket FromGcpBackupBucketProperties(GcpBackupBucketProperties gcpBackupBucketProperties)
        {
            return new GcpBackupBucketPropertiesCase().Set(gcpBackupBucketProperties);
        }

        /// <summary>
        /// This is AzureBackupBucketProperties case.
        /// </summary>
        /// <returns>
        /// The BackupBucket instance, wrapping the provided AzureBackupBucketProperties value.
        /// </returns>
        public static BackupBucket FromAzureBackupBucketProperties(AzureBackupBucketProperties azureBackupBucketProperties)
        {
            return new AzureBackupBucketPropertiesCase().Set(azureBackupBucketProperties);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<AwsBackupBucketProperties, T> awsBackupBucketProperties,
            Func<GcpBackupBucketProperties, T> gcpBackupBucketProperties,
            Func<AzureBackupBucketProperties, T> azureBackupBucketProperties);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<AwsBackupBucketProperties, T> awsBackupBucketProperties = null,
            Func<GcpBackupBucketProperties, T> gcpBackupBucketProperties = null,
            Func<AzureBackupBucketProperties, T> azureBackupBucketProperties = null) =>
                Match(awsBackupBucketProperties, gcpBackupBucketProperties, azureBackupBucketProperties);

        [JsonConverter(typeof(UnionTypeCaseConverter<AwsBackupBucketPropertiesCase, AwsBackupBucketProperties>))]
        private sealed class AwsBackupBucketPropertiesCase : BackupBucket, ICaseValue<AwsBackupBucketPropertiesCase, AwsBackupBucketProperties>
        {
            public AwsBackupBucketProperties Value;

            public override T Match<T>(
                Func<AwsBackupBucketProperties, T> awsBackupBucketProperties,
                Func<GcpBackupBucketProperties, T> gcpBackupBucketProperties,
                Func<AzureBackupBucketProperties, T> azureBackupBucketProperties) =>
                   awsBackupBucketProperties != null ? awsBackupBucketProperties(Value) : default;

            public AwsBackupBucketPropertiesCase Set(AwsBackupBucketProperties value)
            {
                Value = value;
                return this;
            }

            public AwsBackupBucketProperties Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<GcpBackupBucketPropertiesCase, GcpBackupBucketProperties>))]
        private sealed class GcpBackupBucketPropertiesCase : BackupBucket, ICaseValue<GcpBackupBucketPropertiesCase, GcpBackupBucketProperties>
        {
            public GcpBackupBucketProperties Value;

            public override T Match<T>(
                Func<AwsBackupBucketProperties, T> awsBackupBucketProperties,
                Func<GcpBackupBucketProperties, T> gcpBackupBucketProperties,
                Func<AzureBackupBucketProperties, T> azureBackupBucketProperties) =>
                   gcpBackupBucketProperties != null ? gcpBackupBucketProperties(Value) : default;

            public GcpBackupBucketPropertiesCase Set(GcpBackupBucketProperties value)
            {
                Value = value;
                return this;
            }

            public GcpBackupBucketProperties Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<AzureBackupBucketPropertiesCase, AzureBackupBucketProperties>))]
        private sealed class AzureBackupBucketPropertiesCase : BackupBucket, ICaseValue<AzureBackupBucketPropertiesCase, AzureBackupBucketProperties>
        {
            public AzureBackupBucketProperties Value;

            public override T Match<T>(
                Func<AwsBackupBucketProperties, T> awsBackupBucketProperties,
                Func<GcpBackupBucketProperties, T> gcpBackupBucketProperties,
                Func<AzureBackupBucketProperties, T> azureBackupBucketProperties) =>
                   azureBackupBucketProperties != null ? azureBackupBucketProperties(Value) : default;

            public AzureBackupBucketPropertiesCase Set(AzureBackupBucketProperties value)
            {
                Value = value;
                return this;
            }

            public AzureBackupBucketProperties Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}