// <copyright file="ClickStackDashboardChartSeries.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace OpenApiSpecForClickHouseCloud.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<ClickStackDashboardChartSeries>),
        new System.Type[] {
            typeof(ClickStackTimeChartSeriesCase),
            typeof(ClickStackTableChartSeriesCase),
            typeof(ClickStackNumberChartSeriesCase),
            typeof(ClickStackSearchChartSeriesCase),
            typeof(ClickStackMarkdownChartSeriesCase)
        },
        true
    )]
    public abstract class ClickStackDashboardChartSeries
    {
        /// <summary>
        /// This is ClickStackTimeChartSeries case.
        /// </summary>
        /// <returns>
        /// The ClickStackDashboardChartSeries instance, wrapping the provided ClickStackTimeChartSeries value.
        /// </returns>
        public static ClickStackDashboardChartSeries FromClickStackTimeChartSeries(ClickStackTimeChartSeries clickStackTimeChartSeries)
        {
            return new ClickStackTimeChartSeriesCase().Set(clickStackTimeChartSeries);
        }

        /// <summary>
        /// This is ClickStackTableChartSeries case.
        /// </summary>
        /// <returns>
        /// The ClickStackDashboardChartSeries instance, wrapping the provided ClickStackTableChartSeries value.
        /// </returns>
        public static ClickStackDashboardChartSeries FromClickStackTableChartSeries(ClickStackTableChartSeries clickStackTableChartSeries)
        {
            return new ClickStackTableChartSeriesCase().Set(clickStackTableChartSeries);
        }

        /// <summary>
        /// This is ClickStackNumberChartSeries case.
        /// </summary>
        /// <returns>
        /// The ClickStackDashboardChartSeries instance, wrapping the provided ClickStackNumberChartSeries value.
        /// </returns>
        public static ClickStackDashboardChartSeries FromClickStackNumberChartSeries(ClickStackNumberChartSeries clickStackNumberChartSeries)
        {
            return new ClickStackNumberChartSeriesCase().Set(clickStackNumberChartSeries);
        }

        /// <summary>
        /// This is ClickStackSearchChartSeries case.
        /// </summary>
        /// <returns>
        /// The ClickStackDashboardChartSeries instance, wrapping the provided ClickStackSearchChartSeries value.
        /// </returns>
        public static ClickStackDashboardChartSeries FromClickStackSearchChartSeries(ClickStackSearchChartSeries clickStackSearchChartSeries)
        {
            return new ClickStackSearchChartSeriesCase().Set(clickStackSearchChartSeries);
        }

        /// <summary>
        /// This is ClickStackMarkdownChartSeries case.
        /// </summary>
        /// <returns>
        /// The ClickStackDashboardChartSeries instance, wrapping the provided ClickStackMarkdownChartSeries value.
        /// </returns>
        public static ClickStackDashboardChartSeries FromClickStackMarkdownChartSeries(ClickStackMarkdownChartSeries clickStackMarkdownChartSeries)
        {
            return new ClickStackMarkdownChartSeriesCase().Set(clickStackMarkdownChartSeries);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries,
            Func<ClickStackTableChartSeries, T> clickStackTableChartSeries,
            Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries,
            Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries,
            Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries = null,
            Func<ClickStackTableChartSeries, T> clickStackTableChartSeries = null,
            Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries = null,
            Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries = null,
            Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries = null) =>
                Match(clickStackTimeChartSeries, clickStackTableChartSeries, clickStackNumberChartSeries, clickStackSearchChartSeries, clickStackMarkdownChartSeries);

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackTimeChartSeriesCase, ClickStackTimeChartSeries>))]
        private sealed class ClickStackTimeChartSeriesCase : ClickStackDashboardChartSeries, ICaseValue<ClickStackTimeChartSeriesCase, ClickStackTimeChartSeries>
        {
            public ClickStackTimeChartSeries Value;

            public override T Match<T>(
                Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries,
                Func<ClickStackTableChartSeries, T> clickStackTableChartSeries,
                Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries,
                Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries,
                Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries) =>
                   clickStackTimeChartSeries != null ? clickStackTimeChartSeries(Value) : default;

            public ClickStackTimeChartSeriesCase Set(ClickStackTimeChartSeries value)
            {
                Value = value;
                return this;
            }

            public ClickStackTimeChartSeries Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackTableChartSeriesCase, ClickStackTableChartSeries>))]
        private sealed class ClickStackTableChartSeriesCase : ClickStackDashboardChartSeries, ICaseValue<ClickStackTableChartSeriesCase, ClickStackTableChartSeries>
        {
            public ClickStackTableChartSeries Value;

            public override T Match<T>(
                Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries,
                Func<ClickStackTableChartSeries, T> clickStackTableChartSeries,
                Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries,
                Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries,
                Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries) =>
                   clickStackTableChartSeries != null ? clickStackTableChartSeries(Value) : default;

            public ClickStackTableChartSeriesCase Set(ClickStackTableChartSeries value)
            {
                Value = value;
                return this;
            }

            public ClickStackTableChartSeries Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackNumberChartSeriesCase, ClickStackNumberChartSeries>))]
        private sealed class ClickStackNumberChartSeriesCase : ClickStackDashboardChartSeries, ICaseValue<ClickStackNumberChartSeriesCase, ClickStackNumberChartSeries>
        {
            public ClickStackNumberChartSeries Value;

            public override T Match<T>(
                Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries,
                Func<ClickStackTableChartSeries, T> clickStackTableChartSeries,
                Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries,
                Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries,
                Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries) =>
                   clickStackNumberChartSeries != null ? clickStackNumberChartSeries(Value) : default;

            public ClickStackNumberChartSeriesCase Set(ClickStackNumberChartSeries value)
            {
                Value = value;
                return this;
            }

            public ClickStackNumberChartSeries Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackSearchChartSeriesCase, ClickStackSearchChartSeries>))]
        private sealed class ClickStackSearchChartSeriesCase : ClickStackDashboardChartSeries, ICaseValue<ClickStackSearchChartSeriesCase, ClickStackSearchChartSeries>
        {
            public ClickStackSearchChartSeries Value;

            public override T Match<T>(
                Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries,
                Func<ClickStackTableChartSeries, T> clickStackTableChartSeries,
                Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries,
                Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries,
                Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries) =>
                   clickStackSearchChartSeries != null ? clickStackSearchChartSeries(Value) : default;

            public ClickStackSearchChartSeriesCase Set(ClickStackSearchChartSeries value)
            {
                Value = value;
                return this;
            }

            public ClickStackSearchChartSeries Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackMarkdownChartSeriesCase, ClickStackMarkdownChartSeries>))]
        private sealed class ClickStackMarkdownChartSeriesCase : ClickStackDashboardChartSeries, ICaseValue<ClickStackMarkdownChartSeriesCase, ClickStackMarkdownChartSeries>
        {
            public ClickStackMarkdownChartSeries Value;

            public override T Match<T>(
                Func<ClickStackTimeChartSeries, T> clickStackTimeChartSeries,
                Func<ClickStackTableChartSeries, T> clickStackTableChartSeries,
                Func<ClickStackNumberChartSeries, T> clickStackNumberChartSeries,
                Func<ClickStackSearchChartSeries, T> clickStackSearchChartSeries,
                Func<ClickStackMarkdownChartSeries, T> clickStackMarkdownChartSeries) =>
                   clickStackMarkdownChartSeries != null ? clickStackMarkdownChartSeries(Value) : default;

            public ClickStackMarkdownChartSeriesCase Set(ClickStackMarkdownChartSeries value)
            {
                Value = value;
                return this;
            }

            public ClickStackMarkdownChartSeries Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}