// <copyright file="ClickStackSource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace OpenApiSpecForClickHouseCloud.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<ClickStackSource>),
        new System.Type[] {
            typeof(ClickStackLogSourceCase),
            typeof(ClickStackTraceSourceCase),
            typeof(ClickStackMetricSourceCase),
            typeof(ClickStackSessionSourceCase),
            typeof(ClickStackPromqlSourceCase)
        },
        true
    )]
    public abstract class ClickStackSource
    {
        /// <summary>
        /// This is ClickStackLogSource case.
        /// </summary>
        /// <returns>
        /// The ClickStackSource instance, wrapping the provided ClickStackLogSource value.
        /// </returns>
        public static ClickStackSource FromClickStackLogSource(ClickStackLogSource clickStackLogSource)
        {
            return new ClickStackLogSourceCase().Set(clickStackLogSource);
        }

        /// <summary>
        /// This is ClickStackTraceSource case.
        /// </summary>
        /// <returns>
        /// The ClickStackSource instance, wrapping the provided ClickStackTraceSource value.
        /// </returns>
        public static ClickStackSource FromClickStackTraceSource(ClickStackTraceSource clickStackTraceSource)
        {
            return new ClickStackTraceSourceCase().Set(clickStackTraceSource);
        }

        /// <summary>
        /// This is ClickStackMetricSource case.
        /// </summary>
        /// <returns>
        /// The ClickStackSource instance, wrapping the provided ClickStackMetricSource value.
        /// </returns>
        public static ClickStackSource FromClickStackMetricSource(ClickStackMetricSource clickStackMetricSource)
        {
            return new ClickStackMetricSourceCase().Set(clickStackMetricSource);
        }

        /// <summary>
        /// This is ClickStackSessionSource case.
        /// </summary>
        /// <returns>
        /// The ClickStackSource instance, wrapping the provided ClickStackSessionSource value.
        /// </returns>
        public static ClickStackSource FromClickStackSessionSource(ClickStackSessionSource clickStackSessionSource)
        {
            return new ClickStackSessionSourceCase().Set(clickStackSessionSource);
        }

        /// <summary>
        /// This is ClickStackPromqlSource case.
        /// </summary>
        /// <returns>
        /// The ClickStackSource instance, wrapping the provided ClickStackPromqlSource value.
        /// </returns>
        public static ClickStackSource FromClickStackPromqlSource(ClickStackPromqlSource clickStackPromqlSource)
        {
            return new ClickStackPromqlSourceCase().Set(clickStackPromqlSource);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<ClickStackLogSource, T> clickStackLogSource,
            Func<ClickStackTraceSource, T> clickStackTraceSource,
            Func<ClickStackMetricSource, T> clickStackMetricSource,
            Func<ClickStackSessionSource, T> clickStackSessionSource,
            Func<ClickStackPromqlSource, T> clickStackPromqlSource);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<ClickStackLogSource, T> clickStackLogSource = null,
            Func<ClickStackTraceSource, T> clickStackTraceSource = null,
            Func<ClickStackMetricSource, T> clickStackMetricSource = null,
            Func<ClickStackSessionSource, T> clickStackSessionSource = null,
            Func<ClickStackPromqlSource, T> clickStackPromqlSource = null) =>
                Match(clickStackLogSource, clickStackTraceSource, clickStackMetricSource, clickStackSessionSource, clickStackPromqlSource);

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackLogSourceCase, ClickStackLogSource>))]
        private sealed class ClickStackLogSourceCase : ClickStackSource, ICaseValue<ClickStackLogSourceCase, ClickStackLogSource>
        {
            public ClickStackLogSource Value;

            public override T Match<T>(
                Func<ClickStackLogSource, T> clickStackLogSource,
                Func<ClickStackTraceSource, T> clickStackTraceSource,
                Func<ClickStackMetricSource, T> clickStackMetricSource,
                Func<ClickStackSessionSource, T> clickStackSessionSource,
                Func<ClickStackPromqlSource, T> clickStackPromqlSource) =>
                   clickStackLogSource != null ? clickStackLogSource(Value) : default;

            public ClickStackLogSourceCase Set(ClickStackLogSource value)
            {
                Value = value;
                return this;
            }

            public ClickStackLogSource Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackTraceSourceCase, ClickStackTraceSource>))]
        private sealed class ClickStackTraceSourceCase : ClickStackSource, ICaseValue<ClickStackTraceSourceCase, ClickStackTraceSource>
        {
            public ClickStackTraceSource Value;

            public override T Match<T>(
                Func<ClickStackLogSource, T> clickStackLogSource,
                Func<ClickStackTraceSource, T> clickStackTraceSource,
                Func<ClickStackMetricSource, T> clickStackMetricSource,
                Func<ClickStackSessionSource, T> clickStackSessionSource,
                Func<ClickStackPromqlSource, T> clickStackPromqlSource) =>
                   clickStackTraceSource != null ? clickStackTraceSource(Value) : default;

            public ClickStackTraceSourceCase Set(ClickStackTraceSource value)
            {
                Value = value;
                return this;
            }

            public ClickStackTraceSource Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackMetricSourceCase, ClickStackMetricSource>))]
        private sealed class ClickStackMetricSourceCase : ClickStackSource, ICaseValue<ClickStackMetricSourceCase, ClickStackMetricSource>
        {
            public ClickStackMetricSource Value;

            public override T Match<T>(
                Func<ClickStackLogSource, T> clickStackLogSource,
                Func<ClickStackTraceSource, T> clickStackTraceSource,
                Func<ClickStackMetricSource, T> clickStackMetricSource,
                Func<ClickStackSessionSource, T> clickStackSessionSource,
                Func<ClickStackPromqlSource, T> clickStackPromqlSource) =>
                   clickStackMetricSource != null ? clickStackMetricSource(Value) : default;

            public ClickStackMetricSourceCase Set(ClickStackMetricSource value)
            {
                Value = value;
                return this;
            }

            public ClickStackMetricSource Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackSessionSourceCase, ClickStackSessionSource>))]
        private sealed class ClickStackSessionSourceCase : ClickStackSource, ICaseValue<ClickStackSessionSourceCase, ClickStackSessionSource>
        {
            public ClickStackSessionSource Value;

            public override T Match<T>(
                Func<ClickStackLogSource, T> clickStackLogSource,
                Func<ClickStackTraceSource, T> clickStackTraceSource,
                Func<ClickStackMetricSource, T> clickStackMetricSource,
                Func<ClickStackSessionSource, T> clickStackSessionSource,
                Func<ClickStackPromqlSource, T> clickStackPromqlSource) =>
                   clickStackSessionSource != null ? clickStackSessionSource(Value) : default;

            public ClickStackSessionSourceCase Set(ClickStackSessionSource value)
            {
                Value = value;
                return this;
            }

            public ClickStackSessionSource Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ClickStackPromqlSourceCase, ClickStackPromqlSource>))]
        private sealed class ClickStackPromqlSourceCase : ClickStackSource, ICaseValue<ClickStackPromqlSourceCase, ClickStackPromqlSource>
        {
            public ClickStackPromqlSource Value;

            public override T Match<T>(
                Func<ClickStackLogSource, T> clickStackLogSource,
                Func<ClickStackTraceSource, T> clickStackTraceSource,
                Func<ClickStackMetricSource, T> clickStackMetricSource,
                Func<ClickStackSessionSource, T> clickStackSessionSource,
                Func<ClickStackPromqlSource, T> clickStackPromqlSource) =>
                   clickStackPromqlSource != null ? clickStackPromqlSource(Value) : default;

            public ClickStackPromqlSourceCase Set(ClickStackPromqlSource value)
            {
                Value = value;
                return this;
            }

            public ClickStackPromqlSource Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}