// <copyright file="UdfCreateRequest2.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace OpenApiSpecForClickHouseCloud.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<UdfCreateRequest2>),
        new System.Type[] {
            typeof(UdfCreateRequestCase),
            typeof(UdfCreateRequest1Case)
        },
        true
    )]
    public abstract class UdfCreateRequest2
    {
        /// <summary>
        /// This is UdfCreateRequest case.
        /// </summary>
        /// <returns>
        /// The UdfCreateRequest2 instance, wrapping the provided UdfCreateRequest value.
        /// </returns>
        public static UdfCreateRequest2 FromUdfCreateRequest(UdfCreateRequest udfCreateRequest)
        {
            return new UdfCreateRequestCase().Set(udfCreateRequest);
        }

        /// <summary>
        /// This is UdfCreateRequest1 case.
        /// </summary>
        /// <returns>
        /// The UdfCreateRequest2 instance, wrapping the provided UdfCreateRequest1 value.
        /// </returns>
        public static UdfCreateRequest2 FromUdfCreateRequest1(UdfCreateRequest1 udfCreateRequest1)
        {
            return new UdfCreateRequest1Case().Set(udfCreateRequest1);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<UdfCreateRequest, T> udfCreateRequest, Func<UdfCreateRequest1, T> udfCreateRequest1);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<UdfCreateRequest, T> udfCreateRequest = null, Func<UdfCreateRequest1, T> udfCreateRequest1 = null) =>
                Match(udfCreateRequest, udfCreateRequest1);

        [JsonConverter(typeof(UnionTypeCaseConverter<UdfCreateRequestCase, UdfCreateRequest>))]
        private sealed class UdfCreateRequestCase : UdfCreateRequest2, ICaseValue<UdfCreateRequestCase, UdfCreateRequest>
        {
            public UdfCreateRequest Value;

            public override T Match<T>(Func<UdfCreateRequest, T> udfCreateRequest, Func<UdfCreateRequest1, T> udfCreateRequest1) =>
                   udfCreateRequest != null ? udfCreateRequest(Value) : default;

            public UdfCreateRequestCase Set(UdfCreateRequest value)
            {
                Value = value;
                return this;
            }

            public UdfCreateRequest Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<UdfCreateRequest1Case, UdfCreateRequest1>))]
        private sealed class UdfCreateRequest1Case : UdfCreateRequest2, ICaseValue<UdfCreateRequest1Case, UdfCreateRequest1>
        {
            public UdfCreateRequest1 Value;

            public override T Match<T>(Func<UdfCreateRequest, T> udfCreateRequest, Func<UdfCreateRequest1, T> udfCreateRequest1) =>
                   udfCreateRequest1 != null ? udfCreateRequest1(Value) : default;

            public UdfCreateRequest1Case Set(UdfCreateRequest1 value)
            {
                Value = value;
                return this;
            }

            public UdfCreateRequest1 Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}