// <copyright file="ApiKeyHashData.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ApiKeyHashData.
    /// </summary>
    public class ApiKeyHashData
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyHashData"/> class.
        /// </summary>
        public ApiKeyHashData()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyHashData"/> class.
        /// </summary>
        /// <param name="keyIdHash">keyIdHash.</param>
        /// <param name="keyIdSuffix">keyIdSuffix.</param>
        /// <param name="keySecretHash">keySecretHash.</param>
        public ApiKeyHashData(
            string keyIdHash = null,
            string keyIdSuffix = null,
            string keySecretHash = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.KeyIdHash = keyIdHash;
            this.KeyIdSuffix = keyIdSuffix;
            this.KeySecretHash = keySecretHash;
        }

        /// <summary>
        /// Hash of the key ID.
        /// </summary>
        [JsonProperty("keyIdHash", NullValueHandling = NullValueHandling.Ignore)]
        public string KeyIdHash { get; set; }

        /// <summary>
        /// Last 4 digits of the key ID. Algorithm: echo -n "yourpassword" | sha256sum | tr -d '-' | xxd -r -p | base64
        /// </summary>
        [JsonProperty("keyIdSuffix", NullValueHandling = NullValueHandling.Ignore)]
        public string KeyIdSuffix { get; set; }

        /// <summary>
        /// Hash of the key secret. Algorithm: echo -n "yourpassword" | sha256sum | tr -d '-' | xxd -r -p | base64
        /// </summary>
        [JsonProperty("keySecretHash", NullValueHandling = NullValueHandling.Ignore)]
        public string KeySecretHash { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ApiKeyHashData : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"KeyIdHash = {this.KeyIdHash ?? "null"}");
            toStringOutput.Add($"KeyIdSuffix = {this.KeyIdSuffix ?? "null"}");
            toStringOutput.Add($"KeySecretHash = {this.KeySecretHash ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}