// <copyright file="ApiKeyPatchRequest.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ApiKeyPatchRequest.
    /// </summary>
    public class ApiKeyPatchRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private DateTime? expireAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "expireAt", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyPatchRequest"/> class.
        /// </summary>
        public ApiKeyPatchRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyPatchRequest"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="roles">roles.</param>
        /// <param name="assignedRoleIds">assignedRoleIds.</param>
        /// <param name="expireAt">expireAt.</param>
        /// <param name="state">state.</param>
        /// <param name="ipAccessList">ipAccessList.</param>
        public ApiKeyPatchRequest(
            string name = null,
            List<Models.Role3> roles = null,
            List<Guid> assignedRoleIds = null,
            DateTime? expireAt = null,
            Models.State4? state = null,
            List<Models.IpAccessListEntry> ipAccessList = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Name = name;
            this.Roles = roles;
            this.AssignedRoleIds = assignedRoleIds;

            if (expireAt != null)
            {
                this.ExpireAt = expireAt;
            }
            this.State = state;
            this.IpAccessList = ipAccessList;
        }

        /// <summary>
        /// Name of the key
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// DEPRECATED. Use `assignedRoleIds` instead. List of roles assigned to the key.
        /// </summary>
        [JsonProperty("roles", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Role3> Roles { get; set; }

        /// <summary>
        /// Array of role UUIDs to assign to the API key
        /// </summary>
        [JsonProperty("assignedRoleIds", NullValueHandling = NullValueHandling.Ignore)]
        public List<Guid> AssignedRoleIds { get; set; }

        /// <summary>
        /// Timestamp the key expires. If `null` or is empty the key never expires. ISO-8601.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("expireAt")]
        public DateTime? ExpireAt
        {
            get
            {
                return this.expireAt;
            }

            set
            {
                this.shouldSerialize["expireAt"] = true;
                this.expireAt = value;
            }
        }

        /// <summary>
        /// State of the key: 'enabled', 'disabled'.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.State4? State { get; set; }

        /// <summary>
        /// List of IP addresses allowed to access the API using this key
        /// </summary>
        [JsonProperty("ipAccessList", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.IpAccessListEntry> IpAccessList { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ApiKeyPatchRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetExpireAt()
        {
            this.shouldSerialize["expireAt"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeExpireAt()
        {
            return this.shouldSerialize["expireAt"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Roles = {(this.Roles == null ? "null" : $"[{string.Join(", ", this.Roles)} ]")}");
            toStringOutput.Add($"AssignedRoleIds = {(this.AssignedRoleIds == null ? "null" : $"[{string.Join(", ", this.AssignedRoleIds)} ]")}");
            toStringOutput.Add($"ExpireAt = {(this.ExpireAt == null ? "null" : this.ExpireAt.ToString())}");
            toStringOutput.Add($"State = {(this.State == null ? "null" : this.State.ToString())}");
            toStringOutput.Add($"IpAccessList = {(this.IpAccessList == null ? "null" : $"[{string.Join(", ", this.IpAccessList)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}