// <copyright file="ApiKey.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ApiKey.
    /// </summary>
    public class ApiKey
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private DateTime? expireAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "expireAt", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKey"/> class.
        /// </summary>
        public ApiKey()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKey"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="state">state.</param>
        /// <param name="roles">roles.</param>
        /// <param name="assignedRoles">assignedRoles.</param>
        /// <param name="keySuffix">keySuffix.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="expireAt">expireAt.</param>
        /// <param name="usedAt">usedAt.</param>
        /// <param name="ipAccessList">ipAccessList.</param>
        public ApiKey(
            Guid? id = null,
            string name = null,
            Models.State4? state = null,
            List<Models.Role3> roles = null,
            List<Models.AssignedRole> assignedRoles = null,
            string keySuffix = null,
            DateTime? createdAt = null,
            DateTime? expireAt = null,
            DateTime? usedAt = null,
            List<Models.IpAccessListEntry> ipAccessList = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.Name = name;
            this.State = state;
            this.Roles = roles;
            this.AssignedRoles = assignedRoles;
            this.KeySuffix = keySuffix;
            this.CreatedAt = createdAt;

            if (expireAt != null)
            {
                this.ExpireAt = expireAt;
            }
            this.UsedAt = usedAt;
            this.IpAccessList = ipAccessList;
        }

        /// <summary>
        /// Unique API key ID.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Name of the key
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// State of the key: 'enabled', 'disabled'.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.State4? State { get; set; }

        /// <summary>
        /// DEPRECATED. Use `assignedRoles` instead. List of roles assigned to the key. For organizations that have migrated to custom roles, this field is frozen at the pre-migration value and does not reflect current role assignments.
        /// </summary>
        [JsonProperty("roles", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Role3> Roles { get; set; }

        /// <summary>
        /// Custom roles and System roles assigned to this API key
        /// </summary>
        [JsonProperty("assignedRoles", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.AssignedRole> AssignedRoles { get; set; }

        /// <summary>
        /// Last 4 letters of the key.
        /// </summary>
        [JsonProperty("keySuffix", NullValueHandling = NullValueHandling.Ignore)]
        public string KeySuffix { get; set; }

        /// <summary>
        /// Timestamp the key was created. ISO-8601.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("createdAt", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Timestamp the key expires. If not present, `null` or is empty the key never expires. ISO-8601.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("expireAt")]
        public DateTime? ExpireAt
        {
            get
            {
                return this.expireAt;
            }

            set
            {
                this.shouldSerialize["expireAt"] = true;
                this.expireAt = value;
            }
        }

        /// <summary>
        /// Timestamp the key was used last time, with one-minute precision. If not present the key was never used. ISO-8601.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("usedAt", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? UsedAt { get; set; }

        /// <summary>
        /// List of IP addresses allowed to access the API using this key
        /// </summary>
        [JsonProperty("ipAccessList", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.IpAccessListEntry> IpAccessList { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ApiKey : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetExpireAt()
        {
            this.shouldSerialize["expireAt"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeExpireAt()
        {
            return this.shouldSerialize["expireAt"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"State = {(this.State == null ? "null" : this.State.ToString())}");
            toStringOutput.Add($"Roles = {(this.Roles == null ? "null" : $"[{string.Join(", ", this.Roles)} ]")}");
            toStringOutput.Add($"AssignedRoles = {(this.AssignedRoles == null ? "null" : $"[{string.Join(", ", this.AssignedRoles)} ]")}");
            toStringOutput.Add($"KeySuffix = {this.KeySuffix ?? "null"}");
            toStringOutput.Add($"CreatedAt = {(this.CreatedAt == null ? "null" : this.CreatedAt.ToString())}");
            toStringOutput.Add($"ExpireAt = {(this.ExpireAt == null ? "null" : this.ExpireAt.ToString())}");
            toStringOutput.Add($"UsedAt = {(this.UsedAt == null ? "null" : this.UsedAt.ToString())}");
            toStringOutput.Add($"IpAccessList = {(this.IpAccessList == null ? "null" : $"[{string.Join(", ", this.IpAccessList)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}