// <copyright file="Authentication11.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Authentication11.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Authentication11
    {
        /// <summary>
        /// Basic.
        /// </summary>
        [EnumMember(Value = "basic")]
        Basic,

        /// <summary>
        /// IamRole.
        /// </summary>
        [EnumMember(Value = "IAM_ROLE")]
        IamRole
    }
}