// <copyright file="AwsBackupBucketPostRequestV1.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// AwsBackupBucketPostRequestV1.
    /// </summary>
    public class AwsBackupBucketPostRequestV1
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AwsBackupBucketPostRequestV1"/> class.
        /// </summary>
        public AwsBackupBucketPostRequestV1()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AwsBackupBucketPostRequestV1"/> class.
        /// </summary>
        /// <param name="bucketProvider">bucketProvider.</param>
        /// <param name="bucketPath">bucketPath.</param>
        /// <param name="iamRoleArn">iamRoleArn.</param>
        /// <param name="iamRoleSessionName">iamRoleSessionName.</param>
        public AwsBackupBucketPostRequestV1(
            Models.BucketProvider? bucketProvider = null,
            string bucketPath = null,
            string iamRoleArn = null,
            string iamRoleSessionName = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.BucketProvider = bucketProvider;
            this.BucketPath = bucketPath;
            this.IamRoleArn = iamRoleArn;
            this.IamRoleSessionName = iamRoleSessionName;
        }

        /// <summary>
        /// Bucket provider
        /// </summary>
        [JsonProperty("bucketProvider", NullValueHandling = NullValueHandling.Ignore)]
        public Models.BucketProvider? BucketProvider { get; set; }

        /// <summary>
        /// Bucket path
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("bucketPath", NullValueHandling = NullValueHandling.Ignore)]
        public string BucketPath { get; set; }

        /// <summary>
        /// AWS Role ARN
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("iamRoleArn", NullValueHandling = NullValueHandling.Ignore)]
        public string IamRoleArn { get; set; }

        /// <summary>
        /// AWS Role session name
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("iamRoleSessionName", NullValueHandling = NullValueHandling.Ignore)]
        public string IamRoleSessionName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AwsBackupBucketPostRequestV1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BucketProvider = {(this.BucketProvider == null ? "null" : this.BucketProvider.ToString())}");
            toStringOutput.Add($"BucketPath = {this.BucketPath ?? "null"}");
            toStringOutput.Add($"IamRoleArn = {this.IamRoleArn ?? "null"}");
            toStringOutput.Add($"IamRoleSessionName = {this.IamRoleSessionName ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}