// <copyright file="BucketProvider.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// BucketProvider.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum BucketProvider
    {
        /// <summary>
        /// Aws.
        /// </summary>
        [EnumMember(Value = "AWS")]
        Aws
    }
}