// <copyright file="ClickPipeMutateMongoDbSource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipeMutateMongoDbSource.
    /// </summary>
    public class ClickPipeMutateMongoDbSource
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipeMutateMongoDbSource"/> class.
        /// </summary>
        public ClickPipeMutateMongoDbSource()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipeMutateMongoDbSource"/> class.
        /// </summary>
        /// <param name="uri">uri.</param>
        /// <param name="readPreference">readPreference.</param>
        /// <param name="settings">settings.</param>
        /// <param name="tableMappings">tableMappings.</param>
        /// <param name="credentials">credentials.</param>
        /// <param name="tlsHost">tlsHost.</param>
        /// <param name="disableTls">disableTls.</param>
        /// <param name="skipCertVerification">skipCertVerification.</param>
        /// <param name="caCertificate">caCertificate.</param>
        public ClickPipeMutateMongoDbSource(
            string uri,
            Models.ReadPreference readPreference,
            Models.ClickPipeMongoDbPipeSettings settings,
            List<Models.ClickPipeMongoDbPipeTableMapping> tableMappings,
            Models.Plain credentials = null,
            string tlsHost = null,
            bool? disableTls = false,
            bool? skipCertVerification = null,
            string caCertificate = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Credentials = credentials;
            this.Uri = uri;
            this.ReadPreference = readPreference;
            this.TlsHost = tlsHost;
            this.DisableTls = disableTls;
            this.SkipCertVerification = skipCertVerification;
            this.CaCertificate = caCertificate;
            this.Settings = settings;
            this.TableMappings = tableMappings;
        }

        /// <summary>
        /// Gets or sets Credentials.
        /// </summary>
        [JsonProperty("credentials", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Plain Credentials { get; set; }

        /// <summary>
        /// MongoDB connection URI. Supports both standard URIs (mongodb://...) and SRV URIs (mongodb+srv://...). Embedded credentials are redacted from API responses, so the returned value can differ from what was submitted.
        /// </summary>
        [JsonProperty("uri")]
        public string Uri { get; set; }

        /// <summary>
        /// MongoDB read preference for replica set reads.
        /// </summary>
        [JsonProperty("readPreference")]
        public Models.ReadPreference ReadPreference { get; set; }

        /// <summary>
        /// TLS/SSL host for secure connections.
        /// </summary>
        [JsonProperty("tlsHost", NullValueHandling = NullValueHandling.Ignore)]
        public string TlsHost { get; set; }

        /// <summary>
        /// Disable TLS for the MongoDB connection. Defaults to false (TLS enabled).
        /// </summary>
        [JsonProperty("disableTls", NullValueHandling = NullValueHandling.Ignore)]
        public bool? DisableTls { get; set; }

        /// <summary>
        /// Skip TLS certificate verification for the MongoDB connection. Use with caution in production environments.
        /// </summary>
        [JsonProperty("skipCertVerification", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SkipCertVerification { get; set; }

        /// <summary>
        /// PEM encoded CA certificate to validate the MongoDB server certificate.
        /// </summary>
        [JsonProperty("caCertificate", NullValueHandling = NullValueHandling.Ignore)]
        public string CaCertificate { get; set; }

        /// <summary>
        /// Gets or sets Settings.
        /// </summary>
        [JsonProperty("settings")]
        public Models.ClickPipeMongoDbPipeSettings Settings { get; set; }

        /// <summary>
        /// List of collection mappings defining which MongoDB collections to replicate and how they map to ClickHouse tables.
        /// </summary>
        [JsonProperty("tableMappings")]
        public List<Models.ClickPipeMongoDbPipeTableMapping> TableMappings { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipeMutateMongoDbSource : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Credentials = {(this.Credentials == null ? "null" : this.Credentials.ToString())}");
            toStringOutput.Add($"Uri = {this.Uri ?? "null"}");
            toStringOutput.Add($"ReadPreference = {this.ReadPreference}");
            toStringOutput.Add($"TlsHost = {this.TlsHost ?? "null"}");
            toStringOutput.Add($"DisableTls = {(this.DisableTls == null ? "null" : this.DisableTls.ToString())}");
            toStringOutput.Add($"SkipCertVerification = {(this.SkipCertVerification == null ? "null" : this.SkipCertVerification.ToString())}");
            toStringOutput.Add($"CaCertificate = {this.CaCertificate ?? "null"}");
            toStringOutput.Add($"Settings = {(this.Settings == null ? "null" : this.Settings.ToString())}");
            toStringOutput.Add($"TableMappings = {(this.TableMappings == null ? "null" : $"[{string.Join(", ", this.TableMappings)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}