// <copyright file="ClickStackTableBuilderChartConfig.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Models.Containers;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackTableBuilderChartConfig.
    /// </summary>
    public class ClickStackTableBuilderChartConfig
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackTableBuilderChartConfig"/> class.
        /// </summary>
        public ClickStackTableBuilderChartConfig()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackTableBuilderChartConfig"/> class.
        /// </summary>
        /// <param name="displayType">displayType.</param>
        /// <param name="sourceId">sourceId.</param>
        /// <param name="mSelect">select.</param>
        /// <param name="groupBy">groupBy.</param>
        /// <param name="having">having.</param>
        /// <param name="orderBy">orderBy.</param>
        /// <param name="asRatio">asRatio.</param>
        /// <param name="numberFormat">numberFormat.</param>
        /// <param name="groupByColumnsOnLeft">groupByColumnsOnLeft.</param>
        /// <param name="onClick">onClick.</param>
        /// <param name="formulas">formulas.</param>
        /// <param name="showOperandSeries">showOperandSeries.</param>
        public ClickStackTableBuilderChartConfig(
            string displayType,
            string sourceId,
            List<Models.ClickStackSelectItem> mSelect,
            string groupBy = null,
            string having = null,
            string orderBy = null,
            bool? asRatio = null,
            Models.ClickStackNumberFormat numberFormat = null,
            bool? groupByColumnsOnLeft = null,
            ClickStackOnClick onClick = null,
            List<Models.ClickStackFormula> formulas = null,
            bool? showOperandSeries = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DisplayType = displayType;
            this.SourceId = sourceId;
            this.MSelect = mSelect;
            this.GroupBy = groupBy;
            this.Having = having;
            this.OrderBy = orderBy;
            this.AsRatio = asRatio;
            this.NumberFormat = numberFormat;
            this.GroupByColumnsOnLeft = groupByColumnsOnLeft;
            this.OnClick = onClick;
            this.Formulas = formulas;
            this.ShowOperandSeries = showOperandSeries;
        }

        /// <summary>
        /// Display type discriminator. Must be "table" for table charts.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("displayType")]
        [JsonRequired]
        public string DisplayType { get; set; }

        /// <summary>
        /// ID of the data source to query.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("sourceId")]
        [JsonRequired]
        public string SourceId { get; set; }

        /// <summary>
        /// One or more aggregated values to display as table columns. When asRatio is true, exactly two select items are required.
        /// </summary>
        [JsonProperty("select")]
        [JsonRequired]
        public List<Models.ClickStackSelectItem> MSelect { get; set; }

        /// <summary>
        /// Field expression to group results by (one row per group value).
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("groupBy", NullValueHandling = NullValueHandling.Ignore)]
        public string GroupBy { get; set; }

        /// <summary>
        /// Post-aggregation SQL HAVING condition.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("having", NullValueHandling = NullValueHandling.Ignore)]
        public string Having { get; set; }

        /// <summary>
        /// SQL ORDER BY expression for sorting table rows.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("orderBy", NullValueHandling = NullValueHandling.Ignore)]
        public string OrderBy { get; set; }

        /// <summary>
        /// Display select[0] / select[1] as a ratio. Requires exactly two select items.
        /// </summary>
        [JsonProperty("asRatio", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AsRatio { get; set; }

        /// <summary>
        /// Gets or sets NumberFormat.
        /// </summary>
        [JsonProperty("numberFormat", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ClickStackNumberFormat NumberFormat { get; set; }

        /// <summary>
        /// When true, render Group By columns to the left of series columns in the table. Defaults to false (Group By columns on the right).
        /// </summary>
        [JsonProperty("groupByColumnsOnLeft", NullValueHandling = NullValueHandling.Ignore)]
        public bool? GroupByColumnsOnLeft { get; set; }

        /// <summary>
        /// Gets or sets OnClick.
        /// </summary>
        [JsonProperty("onClick", NullValueHandling = NullValueHandling.Ignore)]
        public ClickStackOnClick OnClick { get; set; }

        /// <summary>
        /// Derived columns computed from the select items via letter-ref arithmetic ("A" = select[0], "B" = select[1], ...). Metric, log, and trace sources only. Cannot be combined with asRatio.
        /// </summary>
        [JsonProperty("formulas", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ClickStackFormula> Formulas { get; set; }

        /// <summary>
        /// Only meaningful with formulas. When false, only the formula columns are returned; the raw operand columns are hidden.
        /// </summary>
        [JsonProperty("showOperandSeries", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ShowOperandSeries { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackTableBuilderChartConfig : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DisplayType = {this.DisplayType ?? "null"}");
            toStringOutput.Add($"SourceId = {this.SourceId ?? "null"}");
            toStringOutput.Add($"MSelect = {(this.MSelect == null ? "null" : $"[{string.Join(", ", this.MSelect)} ]")}");
            toStringOutput.Add($"GroupBy = {this.GroupBy ?? "null"}");
            toStringOutput.Add($"Having = {this.Having ?? "null"}");
            toStringOutput.Add($"OrderBy = {this.OrderBy ?? "null"}");
            toStringOutput.Add($"AsRatio = {(this.AsRatio == null ? "null" : this.AsRatio.ToString())}");
            toStringOutput.Add($"NumberFormat = {(this.NumberFormat == null ? "null" : this.NumberFormat.ToString())}");
            toStringOutput.Add($"GroupByColumnsOnLeft = {(this.GroupByColumnsOnLeft == null ? "null" : this.GroupByColumnsOnLeft.ToString())}");
            toStringOutput.Add($"OnClick = {(this.OnClick == null ? "null" : this.OnClick.ToString())}");
            toStringOutput.Add($"Formulas = {(this.Formulas == null ? "null" : $"[{string.Join(", ", this.Formulas)} ]")}");
            toStringOutput.Add($"ShowOperandSeries = {(this.ShowOperandSeries == null ? "null" : this.ShowOperandSeries.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}