// <copyright file="ClickPipePatchPostgresSource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipePatchPostgresSource.
    /// </summary>
    public class ClickPipePatchPostgresSource
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string host;
        private int? port;
        private string database;
        private string tlsHost;
        private string caCertificate;
        private bool? disableTls;
        private bool? skipCertVerification;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "host", false },
            { "port", false },
            { "database", false },
            { "tlsHost", false },
            { "caCertificate", false },
            { "disableTls", false },
            { "skipCertVerification", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePatchPostgresSource"/> class.
        /// </summary>
        public ClickPipePatchPostgresSource()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePatchPostgresSource"/> class.
        /// </summary>
        /// <param name="credentials">credentials.</param>
        /// <param name="host">host.</param>
        /// <param name="port">port.</param>
        /// <param name="database">database.</param>
        /// <param name="tlsHost">tlsHost.</param>
        /// <param name="caCertificate">caCertificate.</param>
        /// <param name="disableTls">disableTls.</param>
        /// <param name="skipCertVerification">skipCertVerification.</param>
        /// <param name="settings">settings.</param>
        /// <param name="tableMappingsToAdd">tableMappingsToAdd.</param>
        /// <param name="tableMappingsToRemove">tableMappingsToRemove.</param>
        public ClickPipePatchPostgresSource(
            Models.Plain credentials = null,
            string host = null,
            int? port = null,
            string database = null,
            string tlsHost = null,
            string caCertificate = null,
            bool? disableTls = null,
            bool? skipCertVerification = null,
            Models.ClickPipePatchPostgresPipeSettings settings = null,
            List<Models.ClickPipePostgresPipeTableMapping> tableMappingsToAdd = null,
            List<Models.ClickPipePatchPostgresPipeRemoveTableMapping> tableMappingsToRemove = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Credentials = credentials;

            if (host != null)
            {
                this.Host = host;
            }

            if (port != null)
            {
                this.Port = port;
            }

            if (database != null)
            {
                this.Database = database;
            }

            if (tlsHost != null)
            {
                this.TlsHost = tlsHost;
            }

            if (caCertificate != null)
            {
                this.CaCertificate = caCertificate;
            }

            if (disableTls != null)
            {
                this.DisableTls = disableTls;
            }

            if (skipCertVerification != null)
            {
                this.SkipCertVerification = skipCertVerification;
            }
            this.Settings = settings;
            this.TableMappingsToAdd = tableMappingsToAdd;
            this.TableMappingsToRemove = tableMappingsToRemove;
        }

        /// <summary>
        /// Gets or sets Credentials.
        /// </summary>
        [JsonProperty("credentials", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Plain Credentials { get; set; }

        /// <summary>
        /// PostgreSQL server hostname or IP address. To use a reverse private endpoint, pass the endpoint hostname here.
        /// </summary>
        [JsonProperty("host")]
        public string Host
        {
            get
            {
                return this.host;
            }

            set
            {
                this.shouldSerialize["host"] = true;
                this.host = value;
            }
        }

        /// <summary>
        /// PostgreSQL server port.
        /// </summary>
        [JsonProperty("port")]
        public int? Port
        {
            get
            {
                return this.port;
            }

            set
            {
                this.shouldSerialize["port"] = true;
                this.port = value;
            }
        }

        /// <summary>
        /// PostgreSQL database name to replicate from.
        /// </summary>
        [JsonProperty("database")]
        public string Database
        {
            get
            {
                return this.database;
            }

            set
            {
                this.shouldSerialize["database"] = true;
                this.database = value;
            }
        }

        /// <summary>
        /// TLS/SSL host for secure connections.
        /// </summary>
        [JsonProperty("tlsHost")]
        public string TlsHost
        {
            get
            {
                return this.tlsHost;
            }

            set
            {
                this.shouldSerialize["tlsHost"] = true;
                this.tlsHost = value;
            }
        }

        /// <summary>
        /// PEM encoded CA certificate to validate the Postgres server certificate.
        /// </summary>
        [JsonProperty("caCertificate")]
        public string CaCertificate
        {
            get
            {
                return this.caCertificate;
            }

            set
            {
                this.shouldSerialize["caCertificate"] = true;
                this.caCertificate = value;
            }
        }

        /// <summary>
        /// Disable TLS for the Postgres connection. Use with caution in production environments.
        /// </summary>
        [JsonProperty("disableTls")]
        public bool? DisableTls
        {
            get
            {
                return this.disableTls;
            }

            set
            {
                this.shouldSerialize["disableTls"] = true;
                this.disableTls = value;
            }
        }

        /// <summary>
        /// Skip TLS certificate verification for the Postgres connection. Use with caution in production environments.
        /// </summary>
        [JsonProperty("skipCertVerification")]
        public bool? SkipCertVerification
        {
            get
            {
                return this.skipCertVerification;
            }

            set
            {
                this.shouldSerialize["skipCertVerification"] = true;
                this.skipCertVerification = value;
            }
        }

        /// <summary>
        /// Gets or sets Settings.
        /// </summary>
        [JsonProperty("settings", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ClickPipePatchPostgresPipeSettings Settings { get; set; }

        /// <summary>
        /// Table mappings to add to the pipe. Can be an empty array if no tables are being added.
        /// </summary>
        [JsonProperty("tableMappingsToAdd", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ClickPipePostgresPipeTableMapping> TableMappingsToAdd { get; set; }

        /// <summary>
        /// Table mappings to remove from the pipe. Only sourceSchemaName, sourceTable, and targetTable are required for removal.
        /// </summary>
        [JsonProperty("tableMappingsToRemove", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ClickPipePatchPostgresPipeRemoveTableMapping> TableMappingsToRemove { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipePatchPostgresSource : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetHost()
        {
            this.shouldSerialize["host"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPort()
        {
            this.shouldSerialize["port"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDatabase()
        {
            this.shouldSerialize["database"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTlsHost()
        {
            this.shouldSerialize["tlsHost"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCaCertificate()
        {
            this.shouldSerialize["caCertificate"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDisableTls()
        {
            this.shouldSerialize["disableTls"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSkipCertVerification()
        {
            this.shouldSerialize["skipCertVerification"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeHost()
        {
            return this.shouldSerialize["host"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePort()
        {
            return this.shouldSerialize["port"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDatabase()
        {
            return this.shouldSerialize["database"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTlsHost()
        {
            return this.shouldSerialize["tlsHost"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCaCertificate()
        {
            return this.shouldSerialize["caCertificate"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDisableTls()
        {
            return this.shouldSerialize["disableTls"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSkipCertVerification()
        {
            return this.shouldSerialize["skipCertVerification"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Credentials = {(this.Credentials == null ? "null" : this.Credentials.ToString())}");
            toStringOutput.Add($"Host = {this.Host ?? "null"}");
            toStringOutput.Add($"Port = {(this.Port == null ? "null" : this.Port.ToString())}");
            toStringOutput.Add($"Database = {this.Database ?? "null"}");
            toStringOutput.Add($"TlsHost = {this.TlsHost ?? "null"}");
            toStringOutput.Add($"CaCertificate = {this.CaCertificate ?? "null"}");
            toStringOutput.Add($"DisableTls = {(this.DisableTls == null ? "null" : this.DisableTls.ToString())}");
            toStringOutput.Add($"SkipCertVerification = {(this.SkipCertVerification == null ? "null" : this.SkipCertVerification.ToString())}");
            toStringOutput.Add($"Settings = {(this.Settings == null ? "null" : this.Settings.ToString())}");
            toStringOutput.Add($"TableMappingsToAdd = {(this.TableMappingsToAdd == null ? "null" : $"[{string.Join(", ", this.TableMappingsToAdd)} ]")}");
            toStringOutput.Add($"TableMappingsToRemove = {(this.TableMappingsToRemove == null ? "null" : $"[{string.Join(", ", this.TableMappingsToRemove)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}