// <copyright file="ClickStackHighlightedAttributeExpression.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackHighlightedAttributeExpression.
    /// </summary>
    public class ClickStackHighlightedAttributeExpression
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string luceneExpression;
        private string mAlias;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "luceneExpression", false },
            { "alias", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackHighlightedAttributeExpression"/> class.
        /// </summary>
        public ClickStackHighlightedAttributeExpression()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackHighlightedAttributeExpression"/> class.
        /// </summary>
        /// <param name="sqlExpression">sqlExpression.</param>
        /// <param name="luceneExpression">luceneExpression.</param>
        /// <param name="mAlias">alias.</param>
        public ClickStackHighlightedAttributeExpression(
            string sqlExpression,
            string luceneExpression = null,
            string mAlias = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.SqlExpression = sqlExpression;

            if (luceneExpression != null)
            {
                this.LuceneExpression = luceneExpression;
            }

            if (mAlias != null)
            {
                this.MAlias = mAlias;
            }
        }

        /// <summary>
        /// SQL expression for the attribute
        /// </summary>
        [JsonProperty("sqlExpression")]
        public string SqlExpression { get; set; }

        /// <summary>
        /// An optional, Lucene version of the sqlExpression expression. If provided, it is used when searching for this attribute value.
        /// </summary>
        [JsonProperty("luceneExpression")]
        public string LuceneExpression
        {
            get
            {
                return this.luceneExpression;
            }

            set
            {
                this.shouldSerialize["luceneExpression"] = true;
                this.luceneExpression = value;
            }
        }

        /// <summary>
        /// Optional alias for the attribute
        /// </summary>
        [JsonProperty("alias")]
        public string MAlias
        {
            get
            {
                return this.mAlias;
            }

            set
            {
                this.shouldSerialize["alias"] = true;
                this.mAlias = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackHighlightedAttributeExpression : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLuceneExpression()
        {
            this.shouldSerialize["luceneExpression"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAlias()
        {
            this.shouldSerialize["alias"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLuceneExpression()
        {
            return this.shouldSerialize["luceneExpression"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAlias()
        {
            return this.shouldSerialize["alias"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SqlExpression = {this.SqlExpression ?? "null"}");
            toStringOutput.Add($"LuceneExpression = {this.LuceneExpression ?? "null"}");
            toStringOutput.Add($"MAlias = {this.MAlias ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}