// <copyright file="ClickPipePostPubSubWorkloadIdentitySource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipePostPubSubWorkloadIdentitySource.
    /// </summary>
    public class ClickPipePostPubSubWorkloadIdentitySource
    {
        private DateTime? seekTimestamp;
        private string filter;
        private bool? enableOrdering;
        private int? ackDeadline;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "seekTimestamp", false },
            { "filter", false },
            { "enableOrdering", false },
            { "ackDeadline", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePostPubSubWorkloadIdentitySource"/> class.
        /// </summary>
        public ClickPipePostPubSubWorkloadIdentitySource()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePostPubSubWorkloadIdentitySource"/> class.
        /// </summary>
        /// <param name="format">format.</param>
        /// <param name="projectId">projectId.</param>
        /// <param name="topic">topic.</param>
        /// <param name="authentication">authentication.</param>
        /// <param name="seekType">seekType.</param>
        /// <param name="seekTimestamp">seekTimestamp.</param>
        /// <param name="filter">filter.</param>
        /// <param name="enableOrdering">enableOrdering.</param>
        /// <param name="ackDeadline">ackDeadline.</param>
        public ClickPipePostPubSubWorkloadIdentitySource(
            Models.Format6 format,
            string projectId,
            string topic,
            string authentication,
            Models.SeekType seekType,
            DateTime? seekTimestamp = null,
            string filter = null,
            bool? enableOrdering = null,
            int? ackDeadline = null)
        {
            this.Format = format;
            this.ProjectId = projectId;
            this.Topic = topic;
            this.Authentication = authentication;
            this.SeekType = seekType;

            if (seekTimestamp != null)
            {
                this.SeekTimestamp = seekTimestamp;
            }

            if (filter != null)
            {
                this.Filter = filter;
            }

            if (enableOrdering != null)
            {
                this.EnableOrdering = enableOrdering;
            }

            if (ackDeadline != null)
            {
                this.AckDeadline = ackDeadline;
            }
        }

        /// <summary>
        /// Format of messages in the Pub/Sub topic. GCP Pub/Sub ClickPipes are in limited preview — contact support to enable this feature for your organization.
        /// </summary>
        [JsonProperty("format")]
        public Models.Format6 Format { get; set; }

        /// <summary>
        /// GCP project ID that owns the Pub/Sub topic.
        /// </summary>
        [JsonProperty("projectId")]
        public string ProjectId { get; set; }

        /// <summary>
        /// Pub/Sub topic name (not the fully-qualified path).
        /// </summary>
        [JsonProperty("topic")]
        public string Topic { get; set; }

        /// <summary>
        /// SERVICE_ACCOUNT_WORKLOAD_IDENTITY is in Private Preview. ClickPipes uses the GCP service account returned in gcpWorkloadIdentity.principal by the operation with operationId clickPipesServiceContextGet; grant it access to the source resources.
        /// </summary>
        [JsonProperty("authentication")]
        public string Authentication { get; set; }

        /// <summary>
        /// Starting position strategy for consuming the subscription. The seekTimestamp companion is required only when seekType is "timestamp"; setting it for a mismatched seek type is rejected.
        /// </summary>
        [JsonProperty("seekType")]
        public Models.SeekType SeekType { get; set; }

        /// <summary>
        /// RFC 3339 / ISO 8601 timestamp to seek to. Required when seekType is "timestamp"; must be omitted otherwise.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("seekTimestamp")]
        public DateTime? SeekTimestamp
        {
            get
            {
                return this.seekTimestamp;
            }

            set
            {
                this.shouldSerialize["seekTimestamp"] = true;
                this.seekTimestamp = value;
            }
        }

        /// <summary>
        /// Optional Pub/Sub subscription filter expression (CEL). Maximum 256 characters.
        /// </summary>
        [JsonProperty("filter")]
        public string Filter
        {
            get
            {
                return this.filter;
            }

            set
            {
                this.shouldSerialize["filter"] = true;
                this.filter = value;
            }
        }

        /// <summary>
        /// Whether to enable ordered delivery of messages (requires messages to be published with ordering keys).
        /// </summary>
        [JsonProperty("enableOrdering")]
        public bool? EnableOrdering
        {
            get
            {
                return this.enableOrdering;
            }

            set
            {
                this.shouldSerialize["enableOrdering"] = true;
                this.enableOrdering = value;
            }
        }

        /// <summary>
        /// Acknowledgement deadline for messages, in seconds. Must be between 10 and 600.
        /// </summary>
        [JsonProperty("ackDeadline")]
        public int? AckDeadline
        {
            get
            {
                return this.ackDeadline;
            }

            set
            {
                this.shouldSerialize["ackDeadline"] = true;
                this.ackDeadline = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipePostPubSubWorkloadIdentitySource : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSeekTimestamp()
        {
            this.shouldSerialize["seekTimestamp"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFilter()
        {
            this.shouldSerialize["filter"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEnableOrdering()
        {
            this.shouldSerialize["enableOrdering"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAckDeadline()
        {
            this.shouldSerialize["ackDeadline"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSeekTimestamp()
        {
            return this.shouldSerialize["seekTimestamp"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFilter()
        {
            return this.shouldSerialize["filter"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEnableOrdering()
        {
            return this.shouldSerialize["enableOrdering"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAckDeadline()
        {
            return this.shouldSerialize["ackDeadline"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Format = {this.Format}");
            toStringOutput.Add($"ProjectId = {this.ProjectId ?? "null"}");
            toStringOutput.Add($"Topic = {this.Topic ?? "null"}");
            toStringOutput.Add($"Authentication = {this.Authentication ?? "null"}");
            toStringOutput.Add($"SeekType = {this.SeekType}");
            toStringOutput.Add($"SeekTimestamp = {(this.SeekTimestamp == null ? "null" : this.SeekTimestamp.ToString())}");
            toStringOutput.Add($"Filter = {this.Filter ?? "null"}");
            toStringOutput.Add($"EnableOrdering = {(this.EnableOrdering == null ? "null" : this.EnableOrdering.ToString())}");
            toStringOutput.Add($"AckDeadline = {(this.AckDeadline == null ? "null" : this.AckDeadline.ToString())}");
        }
    }
}