// <copyright file="ClickPipePostKinesisSource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipePostKinesisSource.
    /// </summary>
    public class ClickPipePostKinesisSource
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private bool? useEnhancedFanOut;
        private int? timestamp;
        private string iamRole;
        private Models.MskIamUser accessKey;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "useEnhancedFanOut", false },
            { "timestamp", false },
            { "iamRole", false },
            { "accessKey", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePostKinesisSource"/> class.
        /// </summary>
        public ClickPipePostKinesisSource()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePostKinesisSource"/> class.
        /// </summary>
        /// <param name="format">format.</param>
        /// <param name="streamName">streamName.</param>
        /// <param name="region">region.</param>
        /// <param name="useEnhancedFanOut">useEnhancedFanOut.</param>
        /// <param name="iteratorType">iteratorType.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="authentication">authentication.</param>
        /// <param name="iamRole">iamRole.</param>
        /// <param name="accessKey">accessKey.</param>
        /// <param name="protobufSchema">protobufSchema.</param>
        public ClickPipePostKinesisSource(
            Models.Format2? format = null,
            string streamName = null,
            string region = null,
            bool? useEnhancedFanOut = null,
            Models.IteratorType? iteratorType = null,
            int? timestamp = null,
            Models.Authentication5? authentication = null,
            string iamRole = null,
            Models.MskIamUser accessKey = null,
            string protobufSchema = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Format = format;
            this.StreamName = streamName;
            this.Region = region;

            if (useEnhancedFanOut != null)
            {
                this.UseEnhancedFanOut = useEnhancedFanOut;
            }
            this.IteratorType = iteratorType;

            if (timestamp != null)
            {
                this.Timestamp = timestamp;
            }
            this.Authentication = authentication;

            if (iamRole != null)
            {
                this.IamRole = iamRole;
            }

            if (accessKey != null)
            {
                this.AccessKey = accessKey;
            }
            this.ProtobufSchema = protobufSchema;
        }

        /// <summary>
        /// Format of the Kinesis stream.
        /// </summary>
        [JsonProperty("format", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Format2? Format { get; set; }

        /// <summary>
        /// Name of the Kinesis stream.
        /// </summary>
        [JsonProperty("streamName", NullValueHandling = NullValueHandling.Ignore)]
        public string StreamName { get; set; }

        /// <summary>
        /// AWS region of the Kinesis stream.
        /// </summary>
        [JsonProperty("region", NullValueHandling = NullValueHandling.Ignore)]
        public string Region { get; set; }

        /// <summary>
        /// Use enhanced fan-out for the Kinesis stream.
        /// </summary>
        [JsonProperty("useEnhancedFanOut")]
        public bool? UseEnhancedFanOut
        {
            get
            {
                return this.useEnhancedFanOut;
            }

            set
            {
                this.shouldSerialize["useEnhancedFanOut"] = true;
                this.useEnhancedFanOut = value;
            }
        }

        /// <summary>
        /// Type of iterator to use when reading from the Kinesis stream. If AT_TIMESTAMP is used, the timestamp field must be provided.
        /// </summary>
        [JsonProperty("iteratorType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.IteratorType? IteratorType { get; set; }

        /// <summary>
        /// UNIX timestamp to start reading from the Kinesis stream. Required if iteratorType is AT_TIMESTAMP.
        /// </summary>
        [JsonProperty("timestamp")]
        public int? Timestamp
        {
            get
            {
                return this.timestamp;
            }

            set
            {
                this.shouldSerialize["timestamp"] = true;
                this.timestamp = value;
            }
        }

        /// <summary>
        /// Authentication method to use with the Kinesis stream.
        /// </summary>
        [JsonProperty("authentication", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Authentication5? Authentication { get; set; }

        /// <summary>
        /// IAM role to use for authentication. Required if IAM_ROLE is used.
        /// </summary>
        [JsonProperty("iamRole")]
        public string IamRole
        {
            get
            {
                return this.iamRole;
            }

            set
            {
                this.shouldSerialize["iamRole"] = true;
                this.iamRole = value;
            }
        }

        /// <summary>
        /// Gets or sets AccessKey.
        /// </summary>
        [JsonProperty("accessKey")]
        public Models.MskIamUser AccessKey
        {
            get
            {
                return this.accessKey;
            }

            set
            {
                this.shouldSerialize["accessKey"] = true;
                this.accessKey = value;
            }
        }

        /// <summary>
        /// Base64-encoded .proto source or serialized FileDescriptorSet. Required with Protobuf format and not supported with other formats.
        /// </summary>
        [JsonProperty("protobufSchema", NullValueHandling = NullValueHandling.Ignore)]
        public string ProtobufSchema { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipePostKinesisSource : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUseEnhancedFanOut()
        {
            this.shouldSerialize["useEnhancedFanOut"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTimestamp()
        {
            this.shouldSerialize["timestamp"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetIamRole()
        {
            this.shouldSerialize["iamRole"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccessKey()
        {
            this.shouldSerialize["accessKey"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUseEnhancedFanOut()
        {
            return this.shouldSerialize["useEnhancedFanOut"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTimestamp()
        {
            return this.shouldSerialize["timestamp"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeIamRole()
        {
            return this.shouldSerialize["iamRole"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccessKey()
        {
            return this.shouldSerialize["accessKey"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Format = {(this.Format == null ? "null" : this.Format.ToString())}");
            toStringOutput.Add($"StreamName = {this.StreamName ?? "null"}");
            toStringOutput.Add($"Region = {this.Region ?? "null"}");
            toStringOutput.Add($"UseEnhancedFanOut = {(this.UseEnhancedFanOut == null ? "null" : this.UseEnhancedFanOut.ToString())}");
            toStringOutput.Add($"IteratorType = {(this.IteratorType == null ? "null" : this.IteratorType.ToString())}");
            toStringOutput.Add($"Timestamp = {(this.Timestamp == null ? "null" : this.Timestamp.ToString())}");
            toStringOutput.Add($"Authentication = {(this.Authentication == null ? "null" : this.Authentication.ToString())}");
            toStringOutput.Add($"IamRole = {this.IamRole ?? "null"}");
            toStringOutput.Add($"AccessKey = {(this.AccessKey == null ? "null" : this.AccessKey.ToString())}");
            toStringOutput.Add($"ProtobufSchema = {this.ProtobufSchema ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}