// <copyright file="ClickStackAlertChannelWebhook.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackAlertChannelWebhook.
    /// </summary>
    public class ClickStackAlertChannelWebhook
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string webhookService;
        private string slackChannelId;
        private Models.Severity? severity;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "webhookService", false },
            { "slackChannelId", false },
            { "severity", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackAlertChannelWebhook"/> class.
        /// </summary>
        public ClickStackAlertChannelWebhook()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackAlertChannelWebhook"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="webhookId">webhookId.</param>
        /// <param name="webhookService">webhookService.</param>
        /// <param name="slackChannelId">slackChannelId.</param>
        /// <param name="severity">severity.</param>
        public ClickStackAlertChannelWebhook(
            Models.Type17 type,
            string webhookId,
            string webhookService = null,
            string slackChannelId = null,
            Models.Severity? severity = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.WebhookId = webhookId;

            if (webhookService != null)
            {
                this.WebhookService = webhookService;
            }

            if (slackChannelId != null)
            {
                this.SlackChannelId = slackChannelId;
            }

            if (severity != null)
            {
                this.Severity = severity;
            }
        }

        /// <summary>
        /// Channel type. Must be "webhook" for webhook alerts.
        /// </summary>
        [JsonProperty("type")]
        [JsonRequired]
        public Models.Type17 Type { get; set; }

        /// <summary>
        /// Webhook destination ID.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("webhookId")]
        [JsonRequired]
        public string WebhookId { get; set; }

        /// <summary>
        /// Webhook service type (e.g., slack_api).
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("webhookService")]
        public string WebhookService
        {
            get
            {
                return this.webhookService;
            }

            set
            {
                this.shouldSerialize["webhookService"] = true;
                this.webhookService = value;
            }
        }

        /// <summary>
        /// Slack channel ID for Slack webhooks.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("slackChannelId")]
        public string SlackChannelId
        {
            get
            {
                return this.slackChannelId;
            }

            set
            {
                this.shouldSerialize["slackChannelId"] = true;
                this.slackChannelId = value;
            }
        }

        /// <summary>
        /// Severity label used by PagerDuty API webhooks.
        /// </summary>
        [JsonProperty("severity")]
        public Models.Severity? Severity
        {
            get
            {
                return this.severity;
            }

            set
            {
                this.shouldSerialize["severity"] = true;
                this.severity = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackAlertChannelWebhook : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWebhookService()
        {
            this.shouldSerialize["webhookService"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSlackChannelId()
        {
            this.shouldSerialize["slackChannelId"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSeverity()
        {
            this.shouldSerialize["severity"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWebhookService()
        {
            return this.shouldSerialize["webhookService"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSlackChannelId()
        {
            return this.shouldSerialize["slackChannelId"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSeverity()
        {
            return this.shouldSerialize["severity"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"WebhookId = {this.WebhookId ?? "null"}");
            toStringOutput.Add($"WebhookService = {this.WebhookService ?? "null"}");
            toStringOutput.Add($"SlackChannelId = {this.SlackChannelId ?? "null"}");
            toStringOutput.Add($"Severity = {(this.Severity == null ? "null" : this.Severity.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}