// <copyright file="ClickPipeDestinationTableEngine.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipeDestinationTableEngine.
    /// </summary>
    public class ClickPipeDestinationTableEngine
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string versionColumnId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "versionColumnId", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipeDestinationTableEngine"/> class.
        /// </summary>
        public ClickPipeDestinationTableEngine()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipeDestinationTableEngine"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="versionColumnId">versionColumnId.</param>
        /// <param name="columnIds">columnIds.</param>
        public ClickPipeDestinationTableEngine(
            Models.Type11? type = null,
            string versionColumnId = null,
            List<string> columnIds = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;

            if (versionColumnId != null)
            {
                this.VersionColumnId = versionColumnId;
            }
            this.ColumnIds = columnIds;
        }

        /// <summary>
        /// Engine type of the destination table.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type11? Type { get; set; }

        /// <summary>
        /// Column name to use as version for ReplacingMergeTree engine.
        /// </summary>
        [JsonProperty("versionColumnId")]
        public string VersionColumnId
        {
            get
            {
                return this.versionColumnId;
            }

            set
            {
                this.shouldSerialize["versionColumnId"] = true;
                this.versionColumnId = value;
            }
        }

        /// <summary>
        /// Column names to sum for SummingMergeTree engine.
        /// </summary>
        [JsonProperty("columnIds", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ColumnIds { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipeDestinationTableEngine : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetVersionColumnId()
        {
            this.shouldSerialize["versionColumnId"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeVersionColumnId()
        {
            return this.shouldSerialize["versionColumnId"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"VersionColumnId = {this.VersionColumnId ?? "null"}");
            toStringOutput.Add($"ColumnIds = {(this.ColumnIds == null ? "null" : $"[{string.Join(", ", this.ColumnIds)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}