// <copyright file="ClickPipePatchObjectStorageSource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipePatchObjectStorageSource.
    /// </summary>
    public class ClickPipePatchObjectStorageSource
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private bool? skipInitialLoad;
        private string startAfter;
        private Models.Authentication8? authentication;
        private string iamRole;
        private string connectionString;
        private string path;
        private string azureContainerName;
        private Models.MskIamUser accessKey;
        private string serviceAccountKey;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "skipInitialLoad", false },
            { "startAfter", false },
            { "authentication", false },
            { "iamRole", false },
            { "connectionString", false },
            { "path", false },
            { "azureContainerName", false },
            { "accessKey", false },
            { "serviceAccountKey", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePatchObjectStorageSource"/> class.
        /// </summary>
        public ClickPipePatchObjectStorageSource()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePatchObjectStorageSource"/> class.
        /// </summary>
        /// <param name="skipInitialLoad">skipInitialLoad.</param>
        /// <param name="startAfter">startAfter.</param>
        /// <param name="authentication">authentication.</param>
        /// <param name="iamRole">iamRole.</param>
        /// <param name="connectionString">connectionString.</param>
        /// <param name="path">path.</param>
        /// <param name="azureContainerName">azureContainerName.</param>
        /// <param name="accessKey">accessKey.</param>
        /// <param name="serviceAccountKey">serviceAccountKey.</param>
        public ClickPipePatchObjectStorageSource(
            bool? skipInitialLoad = null,
            string startAfter = null,
            Models.Authentication8? authentication = null,
            string iamRole = null,
            string connectionString = null,
            string path = null,
            string azureContainerName = null,
            Models.MskIamUser accessKey = null,
            string serviceAccountKey = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (skipInitialLoad != null)
            {
                this.SkipInitialLoad = skipInitialLoad;
            }

            if (startAfter != null)
            {
                this.StartAfter = startAfter;
            }

            if (authentication != null)
            {
                this.Authentication = authentication;
            }

            if (iamRole != null)
            {
                this.IamRole = iamRole;
            }

            if (connectionString != null)
            {
                this.ConnectionString = connectionString;
            }

            if (path != null)
            {
                this.Path = path;
            }

            if (azureContainerName != null)
            {
                this.AzureContainerName = azureContainerName;
            }

            if (accessKey != null)
            {
                this.AccessKey = accessKey;
            }

            if (serviceAccountKey != null)
            {
                this.ServiceAccountKey = serviceAccountKey;
            }
        }

        /// <summary>
        /// If set to true, skips the initial load and only ingests files delivered by queue notifications. Only applicable when queueUrl is provided.
        /// </summary>
        [JsonProperty("skipInitialLoad")]
        public bool? SkipInitialLoad
        {
            get
            {
                return this.skipInitialLoad;
            }

            set
            {
                this.shouldSerialize["skipInitialLoad"] = true;
                this.skipInitialLoad = value;
            }
        }

        /// <summary>
        /// Skip all files up to and including this object key during the initial load. Cannot be provided when skipInitialLoad is true.
        /// </summary>
        [JsonProperty("startAfter")]
        public string StartAfter
        {
            get
            {
                return this.startAfter;
            }

            set
            {
                this.shouldSerialize["startAfter"] = true;
                this.startAfter = value;
            }
        }

        /// <summary>
        /// Authentication method. IAM_USER is for S3, GCS, and DigitalOcean Spaces. IAM_ROLE is for S3 only. SERVICE_ACCOUNT is for GCS only. For GCS, SERVICE_ACCOUNT_WORKLOAD_IDENTITY is in Private Preview. ClickPipes uses the GCP service account returned in gcpWorkloadIdentity.principal by the operation with operationId clickPipesServiceContextGet; grant it access to the source resources. CONNECTION_STRING is for Azure Blob Storage. PUBLIC uses no authentication.
        /// </summary>
        [JsonProperty("authentication")]
        public Models.Authentication8? Authentication
        {
            get
            {
                return this.authentication;
            }

            set
            {
                this.shouldSerialize["authentication"] = true;
                this.authentication = value;
            }
        }

        /// <summary>
        /// IAM role to be used with IAM role authentication. Read more in ClickPipes documentation: https://clickhouse.com/docs/en/integrations/clickpipes/object-storage#authentication
        /// </summary>
        [JsonProperty("iamRole")]
        public string IamRole
        {
            get
            {
                return this.iamRole;
            }

            set
            {
                this.shouldSerialize["iamRole"] = true;
                this.iamRole = value;
            }
        }

        /// <summary>
        /// Connection string for Azure Blob Storage authentication. Required when authentication is CONNECTION_STRING.
        /// </summary>
        [JsonProperty("connectionString")]
        public string ConnectionString
        {
            get
            {
                return this.connectionString;
            }

            set
            {
                this.shouldSerialize["connectionString"] = true;
                this.connectionString = value;
            }
        }

        /// <summary>
        /// Path to the file(s) within the Azure container. Used for Azure Blob Storage sources. You can specify multiple files using bash-like wildcards. For more information, see the documentation on using wildcards in path: https://clickhouse.com/docs/en/integrations/clickpipes/object-storage#limitations
        /// </summary>
        [JsonProperty("path")]
        public string Path
        {
            get
            {
                return this.path;
            }

            set
            {
                this.shouldSerialize["path"] = true;
                this.path = value;
            }
        }

        /// <summary>
        /// Container name for Azure Blob Storage. Required when type is azureblobstorage.
        /// </summary>
        [JsonProperty("azureContainerName")]
        public string AzureContainerName
        {
            get
            {
                return this.azureContainerName;
            }

            set
            {
                this.shouldSerialize["azureContainerName"] = true;
                this.azureContainerName = value;
            }
        }

        /// <summary>
        /// Gets or sets AccessKey.
        /// </summary>
        [JsonProperty("accessKey")]
        public Models.MskIamUser AccessKey
        {
            get
            {
                return this.accessKey;
            }

            set
            {
                this.shouldSerialize["accessKey"] = true;
                this.accessKey = value;
            }
        }

        /// <summary>
        /// Base64-encoded GCP service account JSON key. Required when authentication is SERVICE_ACCOUNT.
        /// </summary>
        [JsonProperty("serviceAccountKey")]
        public string ServiceAccountKey
        {
            get
            {
                return this.serviceAccountKey;
            }

            set
            {
                this.shouldSerialize["serviceAccountKey"] = true;
                this.serviceAccountKey = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipePatchObjectStorageSource : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSkipInitialLoad()
        {
            this.shouldSerialize["skipInitialLoad"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStartAfter()
        {
            this.shouldSerialize["startAfter"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAuthentication()
        {
            this.shouldSerialize["authentication"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetIamRole()
        {
            this.shouldSerialize["iamRole"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetConnectionString()
        {
            this.shouldSerialize["connectionString"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPath()
        {
            this.shouldSerialize["path"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAzureContainerName()
        {
            this.shouldSerialize["azureContainerName"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccessKey()
        {
            this.shouldSerialize["accessKey"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetServiceAccountKey()
        {
            this.shouldSerialize["serviceAccountKey"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSkipInitialLoad()
        {
            return this.shouldSerialize["skipInitialLoad"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStartAfter()
        {
            return this.shouldSerialize["startAfter"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAuthentication()
        {
            return this.shouldSerialize["authentication"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeIamRole()
        {
            return this.shouldSerialize["iamRole"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeConnectionString()
        {
            return this.shouldSerialize["connectionString"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePath()
        {
            return this.shouldSerialize["path"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAzureContainerName()
        {
            return this.shouldSerialize["azureContainerName"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccessKey()
        {
            return this.shouldSerialize["accessKey"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeServiceAccountKey()
        {
            return this.shouldSerialize["serviceAccountKey"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SkipInitialLoad = {(this.SkipInitialLoad == null ? "null" : this.SkipInitialLoad.ToString())}");
            toStringOutput.Add($"StartAfter = {this.StartAfter ?? "null"}");
            toStringOutput.Add($"Authentication = {(this.Authentication == null ? "null" : this.Authentication.ToString())}");
            toStringOutput.Add($"IamRole = {this.IamRole ?? "null"}");
            toStringOutput.Add($"ConnectionString = {this.ConnectionString ?? "null"}");
            toStringOutput.Add($"Path = {this.Path ?? "null"}");
            toStringOutput.Add($"AzureContainerName = {this.AzureContainerName ?? "null"}");
            toStringOutput.Add($"AccessKey = {(this.AccessKey == null ? "null" : this.AccessKey.ToString())}");
            toStringOutput.Add($"ServiceAccountKey = {this.ServiceAccountKey ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}