// <copyright file="ClickStackSelectItem.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackSelectItem.
    /// </summary>
    public class ClickStackSelectItem
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackSelectItem"/> class.
        /// </summary>
        public ClickStackSelectItem()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackSelectItem"/> class.
        /// </summary>
        /// <param name="aggFn">aggFn.</param>
        /// <param name="valueExpression">valueExpression.</param>
        /// <param name="mAlias">alias.</param>
        /// <param name="level">level.</param>
        /// <param name="mWhere">where.</param>
        /// <param name="whereLanguage">whereLanguage.</param>
        /// <param name="metricName">metricName.</param>
        /// <param name="metricType">metricType.</param>
        /// <param name="periodAggFn">periodAggFn.</param>
        /// <param name="numberFormat">numberFormat.</param>
        public ClickStackSelectItem(
            Models.AggFn3 aggFn,
            string valueExpression = null,
            string mAlias = null,
            Models.Level? level = null,
            string mWhere = null,
            Models.WhereLanguage4? whereLanguage = null,
            string metricName = null,
            Models.MetricType? metricType = null,
            Models.PeriodAggFn? periodAggFn = null,
            Models.ClickStackNumberFormat numberFormat = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AggFn = aggFn;
            this.ValueExpression = valueExpression;
            this.MAlias = mAlias;
            this.Level = level;
            this.MWhere = mWhere;
            this.WhereLanguage = whereLanguage;
            this.MetricName = metricName;
            this.MetricType = metricType;
            this.PeriodAggFn = periodAggFn;
            this.NumberFormat = numberFormat;
        }

        /// <summary>
        /// Aggregation function to apply. "count" does not require a valueExpression; "quantile" requires a level field indicating the desired percentile (e.g., 0.95).
        /// </summary>
        [JsonProperty("aggFn")]
        public Models.AggFn3 AggFn { get; set; }

        /// <summary>
        /// Expression for the column or value to aggregate. Must be omitted when aggFn is "count"; required for all other aggFn values.
        /// </summary>
        [JsonProperty("valueExpression", NullValueHandling = NullValueHandling.Ignore)]
        public string ValueExpression { get; set; }

        /// <summary>
        /// Display alias for this select item in chart legends.
        /// </summary>
        [JsonProperty("alias", NullValueHandling = NullValueHandling.Ignore)]
        public string MAlias { get; set; }

        /// <summary>
        /// Percentile level; only valid when aggFn is "quantile".
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Level? Level { get; set; }

        /// <summary>
        /// SQL or Lucene filter condition applied before aggregation.
        /// </summary>
        [JsonProperty("where", NullValueHandling = NullValueHandling.Ignore)]
        public string MWhere { get; set; }

        /// <summary>
        /// Query language for the where clause.
        /// </summary>
        [JsonProperty("whereLanguage", NullValueHandling = NullValueHandling.Ignore)]
        public Models.WhereLanguage4? WhereLanguage { get; set; }

        /// <summary>
        /// Name of the metric to aggregate; only applicable when the source is a metrics source.
        /// </summary>
        [JsonProperty("metricName", NullValueHandling = NullValueHandling.Ignore)]
        public string MetricName { get; set; }

        /// <summary>
        /// Metric type; only applicable when the source is a metrics source.
        /// </summary>
        [JsonProperty("metricType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.MetricType? MetricType { get; set; }

        /// <summary>
        /// Optional period aggregation function for Gauge metrics (e.g., compute the delta over the period).
        /// </summary>
        [JsonProperty("periodAggFn", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PeriodAggFn? PeriodAggFn { get; set; }

        /// <summary>
        /// Gets or sets NumberFormat.
        /// </summary>
        [JsonProperty("numberFormat", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ClickStackNumberFormat NumberFormat { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackSelectItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AggFn = {this.AggFn}");
            toStringOutput.Add($"ValueExpression = {this.ValueExpression ?? "null"}");
            toStringOutput.Add($"MAlias = {this.MAlias ?? "null"}");
            toStringOutput.Add($"Level = {(this.Level == null ? "null" : this.Level.ToString())}");
            toStringOutput.Add($"MWhere = {this.MWhere ?? "null"}");
            toStringOutput.Add($"WhereLanguage = {(this.WhereLanguage == null ? "null" : this.WhereLanguage.ToString())}");
            toStringOutput.Add($"MetricName = {this.MetricName ?? "null"}");
            toStringOutput.Add($"MetricType = {(this.MetricType == null ? "null" : this.MetricType.ToString())}");
            toStringOutput.Add($"PeriodAggFn = {(this.PeriodAggFn == null ? "null" : this.PeriodAggFn.ToString())}");
            toStringOutput.Add($"NumberFormat = {(this.NumberFormat == null ? "null" : this.NumberFormat.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}