// <copyright file="ClickStackNumberChartSeries.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackNumberChartSeries.
    /// </summary>
    public class ClickStackNumberChartSeries
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackNumberChartSeries"/> class.
        /// </summary>
        public ClickStackNumberChartSeries()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackNumberChartSeries"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="sourceId">sourceId.</param>
        /// <param name="aggFn">aggFn.</param>
        /// <param name="mWhere">where.</param>
        /// <param name="whereLanguage">whereLanguage.</param>
        /// <param name="level">level.</param>
        /// <param name="field">field.</param>
        /// <param name="mAlias">alias.</param>
        /// <param name="numberFormat">numberFormat.</param>
        /// <param name="metricDataType">metricDataType.</param>
        /// <param name="metricName">metricName.</param>
        public ClickStackNumberChartSeries(
            string type,
            string sourceId,
            Models.AggFn aggFn,
            string mWhere,
            Models.WhereLanguage whereLanguage,
            double? level = null,
            string field = null,
            string mAlias = null,
            Models.ClickStackNumberFormat numberFormat = null,
            Models.MetricDataType? metricDataType = null,
            string metricName = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.SourceId = sourceId;
            this.AggFn = aggFn;
            this.Level = level;
            this.Field = field;
            this.MAlias = mAlias;
            this.MWhere = mWhere;
            this.WhereLanguage = whereLanguage;
            this.NumberFormat = numberFormat;
            this.MetricDataType = metricDataType;
            this.MetricName = metricName;
        }

        /// <summary>
        /// Series type discriminator. Must be "number" for single-value number charts.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("type")]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// ID of the data source to query
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("sourceId")]
        [JsonRequired]
        public string SourceId { get; set; }

        /// <summary>
        /// Aggregation function to apply to the field or metric value
        /// </summary>
        [JsonProperty("aggFn")]
        [JsonRequired]
        public Models.AggFn AggFn { get; set; }

        /// <summary>
        /// Percentile level for quantile aggregations (e.g., 0.95 for p95)
        /// </summary>
        [JsonProperty("level", NullValueHandling = NullValueHandling.Ignore)]
        public double? Level { get; set; }

        /// <summary>
        /// Column or expression to aggregate (required for most aggregation functions except count)
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("field", NullValueHandling = NullValueHandling.Ignore)]
        public string Field { get; set; }

        /// <summary>
        /// Display name for the series in the chart
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("alias", NullValueHandling = NullValueHandling.Ignore)]
        public string MAlias { get; set; }

        /// <summary>
        /// Filter query for the data (syntax depends on whereLanguage)
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("where")]
        [JsonRequired]
        public string MWhere { get; set; }

        /// <summary>
        /// Query language for the where clause
        /// </summary>
        [JsonProperty("whereLanguage")]
        [JsonRequired]
        public Models.WhereLanguage WhereLanguage { get; set; }

        /// <summary>
        /// Gets or sets NumberFormat.
        /// </summary>
        [JsonProperty("numberFormat", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ClickStackNumberFormat NumberFormat { get; set; }

        /// <summary>
        /// Metric data type, only for metrics data sources.
        /// </summary>
        [JsonProperty("metricDataType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.MetricDataType? MetricDataType { get; set; }

        /// <summary>
        /// Metric name for metrics data sources.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("metricName", NullValueHandling = NullValueHandling.Ignore)]
        public string MetricName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackNumberChartSeries : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"SourceId = {this.SourceId ?? "null"}");
            toStringOutput.Add($"AggFn = {this.AggFn}");
            toStringOutput.Add($"Level = {(this.Level == null ? "null" : this.Level.ToString())}");
            toStringOutput.Add($"Field = {this.Field ?? "null"}");
            toStringOutput.Add($"MAlias = {this.MAlias ?? "null"}");
            toStringOutput.Add($"MWhere = {this.MWhere ?? "null"}");
            toStringOutput.Add($"WhereLanguage = {this.WhereLanguage}");
            toStringOutput.Add($"NumberFormat = {(this.NumberFormat == null ? "null" : this.NumberFormat.ToString())}");
            toStringOutput.Add($"MetricDataType = {(this.MetricDataType == null ? "null" : this.MetricDataType.ToString())}");
            toStringOutput.Add($"MetricName = {this.MetricName ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}