// <copyright file="ClickPipePatchPubSubSource.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickPipePatchPubSubSource.
    /// </summary>
    public class ClickPipePatchPubSubSource
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private int? ackDeadline;
        private Models.ServiceAccount serviceAccountKey;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "ackDeadline", false },
            { "serviceAccountKey", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePatchPubSubSource"/> class.
        /// </summary>
        public ClickPipePatchPubSubSource()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickPipePatchPubSubSource"/> class.
        /// </summary>
        /// <param name="authentication">authentication.</param>
        /// <param name="ackDeadline">ackDeadline.</param>
        /// <param name="serviceAccountKey">serviceAccountKey.</param>
        public ClickPipePatchPubSubSource(
            Models.Authentication17? authentication = null,
            int? ackDeadline = null,
            Models.ServiceAccount serviceAccountKey = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Authentication = authentication;

            if (ackDeadline != null)
            {
                this.AckDeadline = ackDeadline;
            }

            if (serviceAccountKey != null)
            {
                this.ServiceAccountKey = serviceAccountKey;
            }
        }

        /// <summary>
        /// Authentication method to use with GCP Pub/Sub. SERVICE_ACCOUNT_WORKLOAD_IDENTITY is in Private Preview. ClickPipes uses the GCP service account returned in gcpWorkloadIdentity.principal by the operation with operationId clickPipesServiceContextGet; grant it access to the source resources.
        /// </summary>
        [JsonProperty("authentication", NullValueHandling = NullValueHandling.Include)]
        public Models.Authentication17? Authentication { get; set; }

        /// <summary>
        /// Acknowledgement deadline for messages, in seconds. Must be between 10 and 600.
        /// </summary>
        [JsonProperty("ackDeadline")]
        public int? AckDeadline
        {
            get
            {
                return this.ackDeadline;
            }

            set
            {
                this.shouldSerialize["ackDeadline"] = true;
                this.ackDeadline = value;
            }
        }

        /// <summary>
        /// Gets or sets ServiceAccountKey.
        /// </summary>
        [JsonProperty("serviceAccountKey")]
        public Models.ServiceAccount ServiceAccountKey
        {
            get
            {
                return this.serviceAccountKey;
            }

            set
            {
                this.shouldSerialize["serviceAccountKey"] = true;
                this.serviceAccountKey = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickPipePatchPubSubSource : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAckDeadline()
        {
            this.shouldSerialize["ackDeadline"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetServiceAccountKey()
        {
            this.shouldSerialize["serviceAccountKey"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAckDeadline()
        {
            return this.shouldSerialize["ackDeadline"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeServiceAccountKey()
        {
            return this.shouldSerialize["serviceAccountKey"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Authentication = {(this.Authentication == null ? "null" : this.Authentication.ToString())}");
            toStringOutput.Add($"AckDeadline = {(this.AckDeadline == null ? "null" : this.AckDeadline.ToString())}");
            toStringOutput.Add($"ServiceAccountKey = {(this.ServiceAccountKey == null ? "null" : this.ServiceAccountKey.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}