// <copyright file="ClickStackMetricTables.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackMetricTables.
    /// </summary>
    public class ClickStackMetricTables
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackMetricTables"/> class.
        /// </summary>
        public ClickStackMetricTables()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackMetricTables"/> class.
        /// </summary>
        /// <param name="gauge">gauge.</param>
        /// <param name="histogram">histogram.</param>
        /// <param name="sum">sum.</param>
        /// <param name="summary">summary.</param>
        /// <param name="exponentialHistogram">exponential histogram.</param>
        public ClickStackMetricTables(
            string gauge = null,
            string histogram = null,
            string sum = null,
            string summary = null,
            string exponentialHistogram = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Gauge = gauge;
            this.Histogram = histogram;
            this.Sum = sum;
            this.Summary = summary;
            this.ExponentialHistogram = exponentialHistogram;
        }

        /// <summary>
        /// Table containing gauge metrics data
        /// </summary>
        [JsonProperty("gauge", NullValueHandling = NullValueHandling.Ignore)]
        public string Gauge { get; set; }

        /// <summary>
        /// Table containing histogram metrics data
        /// </summary>
        [JsonProperty("histogram", NullValueHandling = NullValueHandling.Ignore)]
        public string Histogram { get; set; }

        /// <summary>
        /// Table containing sum metrics data
        /// </summary>
        [JsonProperty("sum", NullValueHandling = NullValueHandling.Ignore)]
        public string Sum { get; set; }

        /// <summary>
        /// Table containing summary metrics data. Note - not yet fully supported by HyperDX
        /// </summary>
        [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
        public string Summary { get; set; }

        /// <summary>
        /// Table containing exponential histogram metrics data. Note - not yet fully supported by HyperDX
        /// </summary>
        [JsonProperty("exponential histogram", NullValueHandling = NullValueHandling.Ignore)]
        public string ExponentialHistogram { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackMetricTables : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Gauge = {this.Gauge ?? "null"}");
            toStringOutput.Add($"Histogram = {this.Histogram ?? "null"}");
            toStringOutput.Add($"Sum = {this.Sum ?? "null"}");
            toStringOutput.Add($"Summary = {this.Summary ?? "null"}");
            toStringOutput.Add($"ExponentialHistogram = {this.ExponentialHistogram ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}