// <copyright file="ClickStackSearchChartConfig.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackSearchChartConfig.
    /// </summary>
    public class ClickStackSearchChartConfig
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackSearchChartConfig"/> class.
        /// </summary>
        public ClickStackSearchChartConfig()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackSearchChartConfig"/> class.
        /// </summary>
        /// <param name="displayType">displayType.</param>
        /// <param name="sourceId">sourceId.</param>
        /// <param name="mSelect">select.</param>
        /// <param name="whereLanguage">whereLanguage.</param>
        /// <param name="mWhere">where.</param>
        public ClickStackSearchChartConfig(
            string displayType,
            string sourceId,
            string mSelect,
            Models.WhereLanguage4 whereLanguage,
            string mWhere = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DisplayType = displayType;
            this.SourceId = sourceId;
            this.MSelect = mSelect;
            this.MWhere = mWhere;
            this.WhereLanguage = whereLanguage;
        }

        /// <summary>
        /// Display type discriminator. Must be "search" for search/log viewer tiles.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("displayType")]
        [JsonRequired]
        public string DisplayType { get; set; }

        /// <summary>
        /// ID of the data source to query.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("sourceId")]
        [JsonRequired]
        public string SourceId { get; set; }

        /// <summary>
        /// Comma-separated list of expressions to display.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("select")]
        [JsonRequired]
        public string MSelect { get; set; }

        /// <summary>
        /// Filter condition for the search (syntax depends on whereLanguage).
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("where", NullValueHandling = NullValueHandling.Ignore)]
        public string MWhere { get; set; }

        /// <summary>
        /// Query language for the where clause.
        /// </summary>
        [JsonProperty("whereLanguage")]
        [JsonRequired]
        public Models.WhereLanguage4 WhereLanguage { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackSearchChartConfig : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DisplayType = {this.DisplayType ?? "null"}");
            toStringOutput.Add($"SourceId = {this.SourceId ?? "null"}");
            toStringOutput.Add($"MSelect = {this.MSelect ?? "null"}");
            toStringOutput.Add($"MWhere = {this.MWhere ?? "null"}");
            toStringOutput.Add($"WhereLanguage = {this.WhereLanguage}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}