// <copyright file="ClickStackAlertResponse.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Models.Containers;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackAlertResponse.
    /// </summary>
    public class ClickStackAlertResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string dashboardId;
        private string tileId;
        private string savedSearchId;
        private string groupBy;
        private double? thresholdMax;
        private int? scheduleOffsetMinutes;
        private DateTime? scheduleStartAt;
        private string name;
        private string message;
        private string note;
        private int? numConsecutiveWindows;
        private Models.ClickStackAlertSilenced silenced;
        private DateTime? createdAt;
        private DateTime? updatedAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "dashboardId", false },
            { "tileId", false },
            { "savedSearchId", false },
            { "groupBy", false },
            { "thresholdMax", false },
            { "scheduleOffsetMinutes", false },
            { "scheduleStartAt", false },
            { "name", false },
            { "message", false },
            { "note", false },
            { "numConsecutiveWindows", false },
            { "silenced", false },
            { "createdAt", false },
            { "updatedAt", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackAlertResponse"/> class.
        /// </summary>
        public ClickStackAlertResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackAlertResponse"/> class.
        /// </summary>
        /// <param name="dashboardId">dashboardId.</param>
        /// <param name="tileId">tileId.</param>
        /// <param name="savedSearchId">savedSearchId.</param>
        /// <param name="groupBy">groupBy.</param>
        /// <param name="threshold">threshold.</param>
        /// <param name="thresholdMax">thresholdMax.</param>
        /// <param name="interval">interval.</param>
        /// <param name="scheduleOffsetMinutes">scheduleOffsetMinutes.</param>
        /// <param name="scheduleStartAt">scheduleStartAt.</param>
        /// <param name="source">source.</param>
        /// <param name="thresholdType">thresholdType.</param>
        /// <param name="channel">channel.</param>
        /// <param name="channels">channels.</param>
        /// <param name="name">name.</param>
        /// <param name="message">message.</param>
        /// <param name="note">note.</param>
        /// <param name="numConsecutiveWindows">numConsecutiveWindows.</param>
        /// <param name="id">id.</param>
        /// <param name="state">state.</param>
        /// <param name="teamId">teamId.</param>
        /// <param name="silenced">silenced.</param>
        /// <param name="executionErrors">executionErrors.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public ClickStackAlertResponse(
            string dashboardId = null,
            string tileId = null,
            string savedSearchId = null,
            string groupBy = null,
            double? threshold = null,
            double? thresholdMax = null,
            Models.Interval? interval = null,
            int? scheduleOffsetMinutes = null,
            DateTime? scheduleStartAt = null,
            Models.Source? source = null,
            Models.ThresholdType? thresholdType = null,
            ClickStackAlertChannel channel = null,
            List<ClickStackAlertChannel> channels = null,
            string name = null,
            string message = null,
            string note = null,
            int? numConsecutiveWindows = null,
            string id = null,
            Models.State3? state = null,
            string teamId = null,
            Models.ClickStackAlertSilenced silenced = null,
            List<Models.ClickStackAlertExecutionError> executionErrors = null,
            DateTime? createdAt = null,
            DateTime? updatedAt = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (dashboardId != null)
            {
                this.DashboardId = dashboardId;
            }

            if (tileId != null)
            {
                this.TileId = tileId;
            }

            if (savedSearchId != null)
            {
                this.SavedSearchId = savedSearchId;
            }

            if (groupBy != null)
            {
                this.GroupBy = groupBy;
            }
            this.Threshold = threshold;

            if (thresholdMax != null)
            {
                this.ThresholdMax = thresholdMax;
            }
            this.Interval = interval;

            if (scheduleOffsetMinutes != null)
            {
                this.ScheduleOffsetMinutes = scheduleOffsetMinutes;
            }

            if (scheduleStartAt != null)
            {
                this.ScheduleStartAt = scheduleStartAt;
            }
            this.Source = source;
            this.ThresholdType = thresholdType;
            this.Channel = channel;
            this.Channels = channels;

            if (name != null)
            {
                this.Name = name;
            }

            if (message != null)
            {
                this.Message = message;
            }

            if (note != null)
            {
                this.Note = note;
            }

            if (numConsecutiveWindows != null)
            {
                this.NumConsecutiveWindows = numConsecutiveWindows;
            }
            this.Id = id;
            this.State = state;
            this.TeamId = teamId;

            if (silenced != null)
            {
                this.Silenced = silenced;
            }
            this.ExecutionErrors = executionErrors;

            if (createdAt != null)
            {
                this.CreatedAt = createdAt;
            }

            if (updatedAt != null)
            {
                this.UpdatedAt = updatedAt;
            }
        }

        /// <summary>
        /// Dashboard ID for tile-based alerts.
        /// </summary>
        [JsonProperty("dashboardId")]
        public string DashboardId
        {
            get
            {
                return this.dashboardId;
            }

            set
            {
                this.shouldSerialize["dashboardId"] = true;
                this.dashboardId = value;
            }
        }

        /// <summary>
        /// Tile ID for tile-based alerts. Must be a line, stacked bar, or number type tile.
        /// </summary>
        [JsonProperty("tileId")]
        public string TileId
        {
            get
            {
                return this.tileId;
            }

            set
            {
                this.shouldSerialize["tileId"] = true;
                this.tileId = value;
            }
        }

        /// <summary>
        /// Saved search ID for saved_search alerts.
        /// </summary>
        [JsonProperty("savedSearchId")]
        public string SavedSearchId
        {
            get
            {
                return this.savedSearchId;
            }

            set
            {
                this.shouldSerialize["savedSearchId"] = true;
                this.savedSearchId = value;
            }
        }

        /// <summary>
        /// Group-by key for saved search alerts.
        /// </summary>
        [JsonProperty("groupBy")]
        public string GroupBy
        {
            get
            {
                return this.groupBy;
            }

            set
            {
                this.shouldSerialize["groupBy"] = true;
                this.groupBy = value;
            }
        }

        /// <summary>
        /// Threshold value for triggering the alert. For between and not_between threshold types, this is the lower bound.
        /// </summary>
        [JsonProperty("threshold", NullValueHandling = NullValueHandling.Ignore)]
        public double? Threshold { get; set; }

        /// <summary>
        /// Upper bound for between and not_between threshold types. Required when thresholdType is between or not_between, must be >= threshold.
        /// </summary>
        [JsonProperty("thresholdMax")]
        public double? ThresholdMax
        {
            get
            {
                return this.thresholdMax;
            }

            set
            {
                this.shouldSerialize["thresholdMax"] = true;
                this.thresholdMax = value;
            }
        }

        /// <summary>
        /// Evaluation interval for the alert. `30s` requires the 30s alert interval feature to be enabled for your team.
        /// </summary>
        [JsonProperty("interval", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Interval? Interval { get; set; }

        /// <summary>
        /// Offset from the interval boundary in minutes. For example, 2 with a 5m interval evaluates windows at :02, :07, :12, etc. (UTC).
        /// </summary>
        [JsonProperty("scheduleOffsetMinutes")]
        public int? ScheduleOffsetMinutes
        {
            get
            {
                return this.scheduleOffsetMinutes;
            }

            set
            {
                this.shouldSerialize["scheduleOffsetMinutes"] = true;
                this.scheduleOffsetMinutes = value;
            }
        }

        /// <summary>
        /// Absolute UTC start time anchor. Alert windows start from this timestamp and repeat every interval.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("scheduleStartAt")]
        public DateTime? ScheduleStartAt
        {
            get
            {
                return this.scheduleStartAt;
            }

            set
            {
                this.shouldSerialize["scheduleStartAt"] = true;
                this.scheduleStartAt = value;
            }
        }

        /// <summary>
        /// Alert source type (tile-based or saved search).
        /// </summary>
        [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Source? Source { get; set; }

        /// <summary>
        /// Threshold comparison direction.
        /// </summary>
        [JsonProperty("thresholdType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThresholdType? ThresholdType { get; set; }

        /// <summary>
        /// Gets or sets Channel.
        /// </summary>
        [JsonProperty("channel", NullValueHandling = NullValueHandling.Ignore)]
        public ClickStackAlertChannel Channel { get; set; }

        /// <summary>
        /// Notification channels to trigger when the alert fires or resolves. Between 1 and 10 channels; duplicates are rejected.
        /// </summary>
        [JsonProperty("channels", NullValueHandling = NullValueHandling.Ignore)]
        public List<ClickStackAlertChannel> Channels { get; set; }

        /// <summary>
        /// Human-friendly alert name.
        /// </summary>
        [JsonProperty("name")]
        public string Name
        {
            get
            {
                return this.name;
            }

            set
            {
                this.shouldSerialize["name"] = true;
                this.name = value;
            }
        }

        /// <summary>
        /// Alert message template.
        /// </summary>
        [JsonProperty("message")]
        public string Message
        {
            get
            {
                return this.message;
            }

            set
            {
                this.shouldSerialize["message"] = true;
                this.message = value;
            }
        }

        /// <summary>
        /// Freeform note for the alert. Supports markdown formatting.
        /// </summary>
        [JsonProperty("note")]
        public string Note
        {
            get
            {
                return this.note;
            }

            set
            {
                this.shouldSerialize["note"] = true;
                this.note = value;
            }
        }

        /// <summary>
        /// Fire the alert only after its condition has been met for this many consecutive evaluation windows. While the condition is met but fewer than this many consecutive windows have violated, the alert is in the PENDING state.
        /// </summary>
        [JsonProperty("numConsecutiveWindows")]
        public int? NumConsecutiveWindows
        {
            get
            {
                return this.numConsecutiveWindows;
            }

            set
            {
                this.shouldSerialize["numConsecutiveWindows"] = true;
                this.numConsecutiveWindows = value;
            }
        }

        /// <summary>
        /// Unique alert identifier.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Current alert state.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.State3? State { get; set; }

        /// <summary>
        /// Team identifier.
        /// </summary>
        [JsonProperty("teamId", NullValueHandling = NullValueHandling.Ignore)]
        public string TeamId { get; set; }

        /// <summary>
        /// Gets or sets Silenced.
        /// </summary>
        [JsonProperty("silenced")]
        public Models.ClickStackAlertSilenced Silenced
        {
            get
            {
                return this.silenced;
            }

            set
            {
                this.shouldSerialize["silenced"] = true;
                this.silenced = value;
            }
        }

        /// <summary>
        /// Errors recorded during the most recent alert execution, if any.
        /// </summary>
        [JsonProperty("executionErrors", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ClickStackAlertExecutionError> ExecutionErrors { get; set; }

        /// <summary>
        /// Creation timestamp.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("createdAt")]
        public DateTime? CreatedAt
        {
            get
            {
                return this.createdAt;
            }

            set
            {
                this.shouldSerialize["createdAt"] = true;
                this.createdAt = value;
            }
        }

        /// <summary>
        /// Last update timestamp.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updatedAt")]
        public DateTime? UpdatedAt
        {
            get
            {
                return this.updatedAt;
            }

            set
            {
                this.shouldSerialize["updatedAt"] = true;
                this.updatedAt = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackAlertResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDashboardId()
        {
            this.shouldSerialize["dashboardId"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTileId()
        {
            this.shouldSerialize["tileId"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSavedSearchId()
        {
            this.shouldSerialize["savedSearchId"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetGroupBy()
        {
            this.shouldSerialize["groupBy"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetThresholdMax()
        {
            this.shouldSerialize["thresholdMax"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetScheduleOffsetMinutes()
        {
            this.shouldSerialize["scheduleOffsetMinutes"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetScheduleStartAt()
        {
            this.shouldSerialize["scheduleStartAt"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetName()
        {
            this.shouldSerialize["name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMessage()
        {
            this.shouldSerialize["message"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNote()
        {
            this.shouldSerialize["note"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNumConsecutiveWindows()
        {
            this.shouldSerialize["numConsecutiveWindows"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSilenced()
        {
            this.shouldSerialize["silenced"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCreatedAt()
        {
            this.shouldSerialize["createdAt"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUpdatedAt()
        {
            this.shouldSerialize["updatedAt"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDashboardId()
        {
            return this.shouldSerialize["dashboardId"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTileId()
        {
            return this.shouldSerialize["tileId"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSavedSearchId()
        {
            return this.shouldSerialize["savedSearchId"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeGroupBy()
        {
            return this.shouldSerialize["groupBy"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeThresholdMax()
        {
            return this.shouldSerialize["thresholdMax"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeScheduleOffsetMinutes()
        {
            return this.shouldSerialize["scheduleOffsetMinutes"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeScheduleStartAt()
        {
            return this.shouldSerialize["scheduleStartAt"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeName()
        {
            return this.shouldSerialize["name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMessage()
        {
            return this.shouldSerialize["message"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNote()
        {
            return this.shouldSerialize["note"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNumConsecutiveWindows()
        {
            return this.shouldSerialize["numConsecutiveWindows"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSilenced()
        {
            return this.shouldSerialize["silenced"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return this.shouldSerialize["createdAt"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return this.shouldSerialize["updatedAt"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DashboardId = {this.DashboardId ?? "null"}");
            toStringOutput.Add($"TileId = {this.TileId ?? "null"}");
            toStringOutput.Add($"SavedSearchId = {this.SavedSearchId ?? "null"}");
            toStringOutput.Add($"GroupBy = {this.GroupBy ?? "null"}");
            toStringOutput.Add($"Threshold = {(this.Threshold == null ? "null" : this.Threshold.ToString())}");
            toStringOutput.Add($"ThresholdMax = {(this.ThresholdMax == null ? "null" : this.ThresholdMax.ToString())}");
            toStringOutput.Add($"Interval = {(this.Interval == null ? "null" : this.Interval.ToString())}");
            toStringOutput.Add($"ScheduleOffsetMinutes = {(this.ScheduleOffsetMinutes == null ? "null" : this.ScheduleOffsetMinutes.ToString())}");
            toStringOutput.Add($"ScheduleStartAt = {(this.ScheduleStartAt == null ? "null" : this.ScheduleStartAt.ToString())}");
            toStringOutput.Add($"Source = {(this.Source == null ? "null" : this.Source.ToString())}");
            toStringOutput.Add($"ThresholdType = {(this.ThresholdType == null ? "null" : this.ThresholdType.ToString())}");
            toStringOutput.Add($"Channel = {(this.Channel == null ? "null" : this.Channel.ToString())}");
            toStringOutput.Add($"Channels = {(this.Channels == null ? "null" : this.Channels.ToString())}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Message = {this.Message ?? "null"}");
            toStringOutput.Add($"Note = {this.Note ?? "null"}");
            toStringOutput.Add($"NumConsecutiveWindows = {(this.NumConsecutiveWindows == null ? "null" : this.NumConsecutiveWindows.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"State = {(this.State == null ? "null" : this.State.ToString())}");
            toStringOutput.Add($"TeamId = {this.TeamId ?? "null"}");
            toStringOutput.Add($"Silenced = {(this.Silenced == null ? "null" : this.Silenced.ToString())}");
            toStringOutput.Add($"ExecutionErrors = {(this.ExecutionErrors == null ? "null" : $"[{string.Join(", ", this.ExecutionErrors)} ]")}");
            toStringOutput.Add($"CreatedAt = {(this.CreatedAt == null ? "null" : this.CreatedAt.ToString())}");
            toStringOutput.Add($"UpdatedAt = {(this.UpdatedAt == null ? "null" : this.UpdatedAt.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}