// <copyright file="ClickStackTraceSourceMetadataMaterializedViews.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ClickStackTraceSourceMetadataMaterializedViews.
    /// </summary>
    public class ClickStackTraceSourceMetadataMaterializedViews
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackTraceSourceMetadataMaterializedViews"/> class.
        /// </summary>
        public ClickStackTraceSourceMetadataMaterializedViews()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClickStackTraceSourceMetadataMaterializedViews"/> class.
        /// </summary>
        /// <param name="keyRollupTable">keyRollupTable.</param>
        /// <param name="kvRollupTable">kvRollupTable.</param>
        /// <param name="granularity">granularity.</param>
        public ClickStackTraceSourceMetadataMaterializedViews(
            string keyRollupTable = null,
            string kvRollupTable = null,
            string granularity = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.KeyRollupTable = keyRollupTable;
            this.KvRollupTable = kvRollupTable;
            this.Granularity = granularity;
        }

        /// <summary>
        /// ClickHouse table name for the key rollup (field discovery).
        /// </summary>
        [JsonProperty("keyRollupTable", NullValueHandling = NullValueHandling.Ignore)]
        public string KeyRollupTable { get; set; }

        /// <summary>
        /// ClickHouse table name for the key-value rollup (value autocomplete).
        /// </summary>
        [JsonProperty("kvRollupTable", NullValueHandling = NullValueHandling.Ignore)]
        public string KvRollupTable { get; set; }

        /// <summary>
        /// The time granularity of the rollup tables.
        /// </summary>
        [JsonProperty("granularity", NullValueHandling = NullValueHandling.Ignore)]
        public string Granularity { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ClickStackTraceSourceMetadataMaterializedViews : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"KeyRollupTable = {this.KeyRollupTable ?? "null"}");
            toStringOutput.Add($"KvRollupTable = {this.KvRollupTable ?? "null"}");
            toStringOutput.Add($"Granularity = {this.Granularity ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}