// <copyright file="DefaultTransactionIsolation.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// DefaultTransactionIsolation.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum DefaultTransactionIsolation
    {
        /// <summary>
        /// EnumReadCommitted.
        /// </summary>
        [EnumMember(Value = "read committed")]
        EnumReadCommitted,

        /// <summary>
        /// EnumRepeatableRead.
        /// </summary>
        [EnumMember(Value = "repeatable read")]
        EnumRepeatableRead,

        /// <summary>
        /// Serializable.
        /// </summary>
        [EnumMember(Value = "serializable")]
        Serializable
    }
}