// <copyright file="DisplayType.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// DisplayType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum DisplayType
    {
        /// <summary>
        /// StackedBar.
        /// </summary>
        [EnumMember(Value = "stacked_bar")]
        StackedBar,

        /// <summary>
        /// Line.
        /// </summary>
        [EnumMember(Value = "line")]
        Line
    }
}