// <copyright file="EntityType.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// EntityType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum EntityType
    {
        /// <summary>
        /// Datawarehouse.
        /// </summary>
        [EnumMember(Value = "datawarehouse")]
        Datawarehouse,

        /// <summary>
        /// Service.
        /// </summary>
        [EnumMember(Value = "service")]
        Service,

        /// <summary>
        /// Clickpipe.
        /// </summary>
        [EnumMember(Value = "clickpipe")]
        Clickpipe
    }
}