// <copyright file="Format6.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Format6.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Format6
    {
        /// <summary>
        /// JsonEachRow.
        /// </summary>
        [EnumMember(Value = "JSONEachRow")]
        JsonEachRow,

        /// <summary>
        /// Avro.
        /// </summary>
        [EnumMember(Value = "Avro")]
        Avro,

        /// <summary>
        /// Protobuf.
        /// </summary>
        [EnumMember(Value = "Protobuf")]
        Protobuf
    }
}