// <copyright file="HeatmapScaleType.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// HeatmapScaleType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum HeatmapScaleType
    {
        /// <summary>
        /// Log.
        /// </summary>
        [EnumMember(Value = "log")]
        Log,

        /// <summary>
        /// Linear.
        /// </summary>
        [EnumMember(Value = "linear")]
        Linear
    }
}