// <copyright file="InstanceServiceQueryApiEndpointsPostRequest.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// InstanceServiceQueryApiEndpointsPostRequest.
    /// </summary>
    public class InstanceServiceQueryApiEndpointsPostRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstanceServiceQueryApiEndpointsPostRequest"/> class.
        /// </summary>
        public InstanceServiceQueryApiEndpointsPostRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstanceServiceQueryApiEndpointsPostRequest"/> class.
        /// </summary>
        /// <param name="roles">roles.</param>
        /// <param name="openApiKeys">openApiKeys.</param>
        /// <param name="allowedOrigins">allowedOrigins.</param>
        public InstanceServiceQueryApiEndpointsPostRequest(
            List<Models.Role> roles = null,
            List<string> openApiKeys = null,
            string allowedOrigins = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Roles = roles;
            this.OpenApiKeys = openApiKeys;
            this.AllowedOrigins = allowedOrigins;
        }

        /// <summary>
        /// The roles
        /// </summary>
        [JsonProperty("roles", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Role> Roles { get; set; }

        /// <summary>
        /// The version of the service query endpoint
        /// </summary>
        [JsonProperty("openApiKeys", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> OpenApiKeys { get; set; }

        /// <summary>
        /// The allowed origins as comma separated list of domains
        /// </summary>
        [JsonProperty("allowedOrigins", NullValueHandling = NullValueHandling.Ignore)]
        public string AllowedOrigins { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstanceServiceQueryApiEndpointsPostRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Roles = {(this.Roles == null ? "null" : $"[{string.Join(", ", this.Roles)} ]")}");
            toStringOutput.Add($"OpenApiKeys = {(this.OpenApiKeys == null ? "null" : $"[{string.Join(", ", this.OpenApiKeys)} ]")}");
            toStringOutput.Add($"AllowedOrigins = {this.AllowedOrigins ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}