// <copyright file="Interval.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Interval.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Interval
    {
        /// <summary>
        /// Enum30S.
        /// </summary>
        [EnumMember(Value = "30s")]
        Enum30S,

        /// <summary>
        /// Enum1M.
        /// </summary>
        [EnumMember(Value = "1m")]
        Enum1M,

        /// <summary>
        /// Enum5M.
        /// </summary>
        [EnumMember(Value = "5m")]
        Enum5M,

        /// <summary>
        /// Enum15M.
        /// </summary>
        [EnumMember(Value = "15m")]
        Enum15M,

        /// <summary>
        /// Enum30M.
        /// </summary>
        [EnumMember(Value = "30m")]
        Enum30M,

        /// <summary>
        /// Enum1H.
        /// </summary>
        [EnumMember(Value = "1h")]
        Enum1H,

        /// <summary>
        /// Enum6H.
        /// </summary>
        [EnumMember(Value = "6h")]
        Enum6H,

        /// <summary>
        /// Enum12H.
        /// </summary>
        [EnumMember(Value = "12h")]
        Enum12H,

        /// <summary>
        /// Enum1D.
        /// </summary>
        [EnumMember(Value = "1d")]
        Enum1D
    }
}