// <copyright file="KeyUpdateType.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// KeyUpdateType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum KeyUpdateType
    {
        /// <summary>
        /// Created.
        /// </summary>
        [EnumMember(Value = "created")]
        Created,

        /// <summary>
        /// Deleted.
        /// </summary>
        [EnumMember(Value = "deleted")]
        Deleted,

        /// <summary>
        /// Namechanged.
        /// </summary>
        [EnumMember(Value = "name-changed")]
        Namechanged,

        /// <summary>
        /// Rolechanged.
        /// </summary>
        [EnumMember(Value = "role-changed")]
        Rolechanged,

        /// <summary>
        /// Statechanged.
        /// </summary>
        [EnumMember(Value = "state-changed")]
        Statechanged,

        /// <summary>
        /// Datechanged.
        /// </summary>
        [EnumMember(Value = "date-changed")]
        Datechanged,

        /// <summary>
        /// Ipaccesslistchanged.
        /// </summary>
        [EnumMember(Value = "ip-access-list-changed")]
        Ipaccesslistchanged,

        /// <summary>
        /// Orgrolechanged.
        /// </summary>
        [EnumMember(Value = "org-role-changed")]
        Orgrolechanged,

        /// <summary>
        /// Defaultservicerolechanged.
        /// </summary>
        [EnumMember(Value = "default-service-role-changed")]
        Defaultservicerolechanged,

        /// <summary>
        /// Servicerolechanged.
        /// </summary>
        [EnumMember(Value = "service-role-changed")]
        Servicerolechanged,

        /// <summary>
        /// Rolesv2Changed.
        /// </summary>
        [EnumMember(Value = "roles-v2-changed")]
        Rolesv2Changed
    }
}