// <copyright file="Level.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Level.
    /// </summary>

    [JsonConverter(typeof(NumberEnumConverter))]
    public enum Level
    {
        /// <summary>
        ///50th percentile.
        /// P50.
        /// </summary>
        P50 = 0,

        /// <summary>
        ///90th percentile.
        /// P90.
        /// </summary>
        P90 = 1,

        /// <summary>
        ///95th percentile.
        /// P95.
        /// </summary>
        P95 = 2,

        /// <summary>
        ///99th percentile.
        /// P99.
        /// </summary>
        P99 = 3
    }
}