// <copyright file="MskAuthentication.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// MskAuthentication.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum MskAuthentication
    {
        /// <summary>
        /// SaslIam.
        /// </summary>
        [EnumMember(Value = "SASL_IAM")]
        SaslIam,

        /// <summary>
        /// SaslScram.
        /// </summary>
        [EnumMember(Value = "SASL_SCRAM")]
        SaslScram
    }
}