// <copyright file="OrganizationQuota.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// OrganizationQuota.
    /// </summary>
    public class OrganizationQuota
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationQuota"/> class.
        /// </summary>
        public OrganizationQuota()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationQuota"/> class.
        /// </summary>
        /// <param name="quotaCode">quotaCode.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="scope">scope.</param>
        /// <param name="mValue">value.</param>
        /// <param name="adjustable">adjustable.</param>
        /// <param name="usage">usage.</param>
        public OrganizationQuota(
            Models.QuotaCode quotaCode,
            string name,
            string description,
            Models.Scope scope,
            int mValue,
            bool adjustable,
            int? usage = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.QuotaCode = quotaCode;
            this.Name = name;
            this.Description = description;
            this.Scope = scope;
            this.MValue = mValue;
            this.Usage = usage;
            this.Adjustable = adjustable;
        }

        /// <summary>
        /// Stable identifier of the quota. Use it to request a single quota by code.
        /// </summary>
        [JsonProperty("quotaCode")]
        public Models.QuotaCode QuotaCode { get; set; }

        /// <summary>
        /// Human-readable name of the quota.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Explanation of the resource the quota limits and how the limit is applied.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }

        /// <summary>
        /// Granularity at which the limit is applied. For example, `replicas-per-warehouse` is an organization-wide setting that limits each warehouse individually.
        /// </summary>
        [JsonProperty("scope")]
        public Models.Scope Scope { get; set; }

        /// <summary>
        /// Limit currently applied to the organization, including any adjustments made for the organization. The value can change when the billing status of the organization changes.
        /// </summary>
        [JsonProperty("value")]
        public int MValue { get; set; }

        /// <summary>
        /// Current consumption of the quota. Omitted for quotas that do not report usage. Usage can exceed `value` when a limit was lowered after resources were created; existing resources are not affected.
        /// </summary>
        [JsonProperty("usage", NullValueHandling = NullValueHandling.Ignore)]
        public int? Usage { get; set; }

        /// <summary>
        /// Whether the limit can be raised for the organization by contacting ClickHouse support.
        /// </summary>
        [JsonProperty("adjustable")]
        public bool Adjustable { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"OrganizationQuota : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"QuotaCode = {this.QuotaCode}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"Scope = {this.Scope}");
            toStringOutput.Add($"MValue = {this.MValue}");
            toStringOutput.Add($"Usage = {(this.Usage == null ? "null" : this.Usage.ToString())}");
            toStringOutput.Add($"Adjustable = {this.Adjustable}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}