// <copyright file="Provider.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Provider.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Provider
    {
        /// <summary>
        /// Aws.
        /// </summary>
        [EnumMember(Value = "aws")]
        Aws,

        /// <summary>
        /// Gcp.
        /// </summary>
        [EnumMember(Value = "gcp")]
        Gcp,

        /// <summary>
        /// Azure.
        /// </summary>
        [EnumMember(Value = "azure")]
        Azure
    }
}