// <copyright file="PublicQueryApiEndpointListItem.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// PublicQueryApiEndpointListItem.
    /// </summary>
    public class PublicQueryApiEndpointListItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicQueryApiEndpointListItem"/> class.
        /// </summary>
        public PublicQueryApiEndpointListItem()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicQueryApiEndpointListItem"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="database">database.</param>
        /// <param name="apiKeyIds">apiKeyIds.</param>
        /// <param name="roles">roles.</param>
        /// <param name="allowedOrigins">allowedOrigins.</param>
        /// <param name="url">url.</param>
        /// <param name="ownerType">ownerType.</param>
        public PublicQueryApiEndpointListItem(
            Guid id,
            string name,
            string database,
            List<Guid> apiKeyIds,
            List<string> roles,
            List<string> allowedOrigins,
            string url,
            Models.OwnerType ownerType)
        {
            this.Id = id;
            this.Name = name;
            this.Database = database;
            this.ApiKeyIds = apiKeyIds;
            this.Roles = roles;
            this.AllowedOrigins = allowedOrigins;
            this.Url = url;
            this.OwnerType = ownerType;
        }

        /// <summary>
        /// Unique ID of the Query API endpoint.
        /// </summary>
        [JsonProperty("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Name of the Query API endpoint.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Database used by the Query API endpoint.
        /// </summary>
        [JsonProperty("database")]
        public string Database { get; set; }

        /// <summary>
        /// API key IDs allowed to call the endpoint.
        /// </summary>
        [JsonProperty("apiKeyIds")]
        public List<Guid> ApiKeyIds { get; set; }

        /// <summary>
        /// Database roles used by the endpoint.
        /// </summary>
        [JsonProperty("roles")]
        public List<string> Roles { get; set; }

        /// <summary>
        /// Origins allowed by the endpoint CORS policy.
        /// </summary>
        [JsonProperty("allowedOrigins")]
        public List<string> AllowedOrigins { get; set; }

        /// <summary>
        /// Public URL used to execute the endpoint.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; }

        /// <summary>
        /// Owner type of the Query API endpoint. Endpoints with a user owned query cannot be updated or deleted through this API.
        /// </summary>
        [JsonProperty("ownerType")]
        public Models.OwnerType OwnerType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PublicQueryApiEndpointListItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Database = {this.Database ?? "null"}");
            toStringOutput.Add($"ApiKeyIds = {(this.ApiKeyIds == null ? "null" : $"[{string.Join(", ", this.ApiKeyIds)} ]")}");
            toStringOutput.Add($"Roles = {(this.Roles == null ? "null" : $"[{string.Join(", ", this.Roles)} ]")}");
            toStringOutput.Add($"AllowedOrigins = {(this.AllowedOrigins == null ? "null" : $"[{string.Join(", ", this.AllowedOrigins)} ]")}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"OwnerType = {this.OwnerType}");
        }
    }
}