// <copyright file="Runtime.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Runtime.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Runtime
    {
        /// <summary>
        /// EnumPython311.
        /// </summary>
        [EnumMember(Value = "python3.11")]
        EnumPython311,

        /// <summary>
        /// Native.
        /// </summary>
        [EnumMember(Value = "native")]
        Native
    }
}