// <copyright file="SandboxType.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// SandboxType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SandboxType
    {
        /// <summary>
        /// Basic.
        /// </summary>
        [EnumMember(Value = "basic")]
        Basic,

        /// <summary>
        /// Netenable.
        /// </summary>
        [EnumMember(Value = "netenable")]
        Netenable
    }
}