// <copyright file="ScimServiceProviderConfig.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// ScimServiceProviderConfig.
    /// </summary>
    public class ScimServiceProviderConfig
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimServiceProviderConfig"/> class.
        /// </summary>
        public ScimServiceProviderConfig()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ScimServiceProviderConfig"/> class.
        /// </summary>
        /// <param name="schemas">schemas.</param>
        /// <param name="patch">patch.</param>
        /// <param name="bulk">bulk.</param>
        /// <param name="filter">filter.</param>
        /// <param name="changePassword">changePassword.</param>
        /// <param name="sort">sort.</param>
        /// <param name="etag">etag.</param>
        /// <param name="authenticationSchemes">authenticationSchemes.</param>
        /// <param name="meta">meta.</param>
        /// <param name="documentationUri">documentationUri.</param>
        public ScimServiceProviderConfig(
            List<string> schemas,
            Models.ScimServiceProviderConfigPatch patch,
            Models.ScimServiceProviderConfigBulk bulk,
            Models.ScimServiceProviderConfigFilter filter,
            Models.ScimBooleanFeature changePassword,
            Models.ScimBooleanFeature sort,
            Models.ScimBooleanFeature etag,
            List<Models.ScimAuthenticationScheme> authenticationSchemes,
            Models.ScimServiceProviderConfigMeta meta,
            string documentationUri = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Schemas = schemas;
            this.DocumentationUri = documentationUri;
            this.Patch = patch;
            this.Bulk = bulk;
            this.Filter = filter;
            this.ChangePassword = changePassword;
            this.Sort = sort;
            this.Etag = etag;
            this.AuthenticationSchemes = authenticationSchemes;
            this.Meta = meta;
        }

        /// <summary>
        /// SCIM schema URIs.
        /// </summary>
        [JsonProperty("schemas")]
        public List<string> Schemas { get; set; }

        /// <summary>
        /// URI of the service documentation.
        /// </summary>
        [JsonProperty("documentationUri", NullValueHandling = NullValueHandling.Ignore)]
        public string DocumentationUri { get; set; }

        /// <summary>
        /// Gets or sets Patch.
        /// </summary>
        [JsonProperty("patch")]
        public Models.ScimServiceProviderConfigPatch Patch { get; set; }

        /// <summary>
        /// Gets or sets Bulk.
        /// </summary>
        [JsonProperty("bulk")]
        public Models.ScimServiceProviderConfigBulk Bulk { get; set; }

        /// <summary>
        /// Gets or sets Filter.
        /// </summary>
        [JsonProperty("filter")]
        public Models.ScimServiceProviderConfigFilter Filter { get; set; }

        /// <summary>
        /// Gets or sets ChangePassword.
        /// </summary>
        [JsonProperty("changePassword")]
        public Models.ScimBooleanFeature ChangePassword { get; set; }

        /// <summary>
        /// Gets or sets Sort.
        /// </summary>
        [JsonProperty("sort")]
        public Models.ScimBooleanFeature Sort { get; set; }

        /// <summary>
        /// Gets or sets Etag.
        /// </summary>
        [JsonProperty("etag")]
        public Models.ScimBooleanFeature Etag { get; set; }

        /// <summary>
        /// Supported authentication schemes.
        /// </summary>
        [JsonProperty("authenticationSchemes")]
        public List<Models.ScimAuthenticationScheme> AuthenticationSchemes { get; set; }

        /// <summary>
        /// Gets or sets Meta.
        /// </summary>
        [JsonProperty("meta")]
        public Models.ScimServiceProviderConfigMeta Meta { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ScimServiceProviderConfig : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Schemas = {(this.Schemas == null ? "null" : $"[{string.Join(", ", this.Schemas)} ]")}");
            toStringOutput.Add($"DocumentationUri = {this.DocumentationUri ?? "null"}");
            toStringOutput.Add($"Patch = {(this.Patch == null ? "null" : this.Patch.ToString())}");
            toStringOutput.Add($"Bulk = {(this.Bulk == null ? "null" : this.Bulk.ToString())}");
            toStringOutput.Add($"Filter = {(this.Filter == null ? "null" : this.Filter.ToString())}");
            toStringOutput.Add($"ChangePassword = {(this.ChangePassword == null ? "null" : this.ChangePassword.ToString())}");
            toStringOutput.Add($"Sort = {(this.Sort == null ? "null" : this.Sort.ToString())}");
            toStringOutput.Add($"Etag = {(this.Etag == null ? "null" : this.Etag.ToString())}");
            toStringOutput.Add($"AuthenticationSchemes = {(this.AuthenticationSchemes == null ? "null" : $"[{string.Join(", ", this.AuthenticationSchemes)} ]")}");
            toStringOutput.Add($"Meta = {(this.Meta == null ? "null" : this.Meta.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}