// <copyright file="SeekType.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// SeekType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SeekType
    {
        /// <summary>
        /// Latest.
        /// </summary>
        [EnumMember(Value = "latest")]
        Latest,

        /// <summary>
        /// Earliest.
        /// </summary>
        [EnumMember(Value = "earliest")]
        Earliest,

        /// <summary>
        /// Timestamp.
        /// </summary>
        [EnumMember(Value = "timestamp")]
        Timestamp
    }
}