// <copyright file="Snapshot.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Models.Containers;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Snapshot.
    /// </summary>
    public class Snapshot
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Snapshot"/> class.
        /// </summary>
        public Snapshot()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Snapshot"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="status">status.</param>
        /// <param name="serviceId">serviceId.</param>
        /// <param name="startedAt">startedAt.</param>
        /// <param name="finishedAt">finishedAt.</param>
        /// <param name="sizeInBytes">sizeInBytes.</param>
        /// <param name="durationInSeconds">durationInSeconds.</param>
        /// <param name="type">type.</param>
        /// <param name="backupName">backupName.</param>
        /// <param name="bucket">bucket.</param>
        public Snapshot(
            Guid? id = null,
            Models.Status2? status = null,
            string serviceId = null,
            DateTime? startedAt = null,
            DateTime? finishedAt = null,
            double? sizeInBytes = null,
            double? durationInSeconds = null,
            Models.Type14? type = null,
            string backupName = null,
            SnapshotBucket bucket = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.Status = status;
            this.ServiceId = serviceId;
            this.StartedAt = startedAt;
            this.FinishedAt = finishedAt;
            this.SizeInBytes = sizeInBytes;
            this.DurationInSeconds = durationInSeconds;
            this.Type = type;
            this.BackupName = backupName;
            this.Bucket = bucket;
        }

        /// <summary>
        /// Unique snapshot ID.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Status of the snapshot: 'done', 'error', 'in_progress', 'throttled'. 'throttled' means snapshot creation was rate-limited and will be retried.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Status2? Status { get; set; }

        /// <summary>
        /// ID of the service the snapshot was created from.
        /// </summary>
        [JsonProperty("serviceId", NullValueHandling = NullValueHandling.Ignore)]
        public string ServiceId { get; set; }

        /// <summary>
        /// Snapshot start timestamp. ISO-8601.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("startedAt", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// Snapshot finish timestamp. ISO-8601. Available only for finished snapshots
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("finishedAt", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? FinishedAt { get; set; }

        /// <summary>
        /// Size of the snapshot in bytes.
        /// </summary>
        [JsonProperty("sizeInBytes", NullValueHandling = NullValueHandling.Ignore)]
        public double? SizeInBytes { get; set; }

        /// <summary>
        /// Time in seconds it took to perform the snapshot. If the status is in_progress or throttled, this is the time in seconds since the snapshot started until now.
        /// </summary>
        [JsonProperty("durationInSeconds", NullValueHandling = NullValueHandling.Ignore)]
        public double? DurationInSeconds { get; set; }

        /// <summary>
        /// Snapshot type. Always "full" — snapshots never chain off a parent.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Type14? Type { get; set; }

        /// <summary>
        /// Snapshot name on the external backup bucket.
        /// </summary>
        [JsonProperty("backupName", NullValueHandling = NullValueHandling.Ignore)]
        public string BackupName { get; set; }

        /// <summary>
        /// Backup bucket where the snapshot is stored.
        /// </summary>
        [JsonProperty("bucket", NullValueHandling = NullValueHandling.Ignore)]
        public SnapshotBucket Bucket { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Snapshot : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"ServiceId = {this.ServiceId ?? "null"}");
            toStringOutput.Add($"StartedAt = {(this.StartedAt == null ? "null" : this.StartedAt.ToString())}");
            toStringOutput.Add($"FinishedAt = {(this.FinishedAt == null ? "null" : this.FinishedAt.ToString())}");
            toStringOutput.Add($"SizeInBytes = {(this.SizeInBytes == null ? "null" : this.SizeInBytes.ToString())}");
            toStringOutput.Add($"DurationInSeconds = {(this.DurationInSeconds == null ? "null" : this.DurationInSeconds.ToString())}");
            toStringOutput.Add($"Type = {(this.Type == null ? "null" : this.Type.ToString())}");
            toStringOutput.Add($"BackupName = {this.BackupName ?? "null"}");
            toStringOutput.Add($"Bucket = {(this.Bucket == null ? "null" : this.Bucket.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}