// <copyright file="SortOrder.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// SortOrder.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SortOrder
    {
        /// <summary>
        /// Desc.
        /// </summary>
        [EnumMember(Value = "desc")]
        Desc,

        /// <summary>
        /// Asc.
        /// </summary>
        [EnumMember(Value = "asc")]
        Asc
    }
}