// <copyright file="State4.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// State4.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum State4
    {
        /// <summary>
        /// Enabled.
        /// </summary>
        [EnumMember(Value = "enabled")]
        Enabled,

        /// <summary>
        /// Disabled.
        /// </summary>
        [EnumMember(Value = "disabled")]
        Disabled
    }
}