// <copyright file="State3.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// State3.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum State3
    {
        /// <summary>
        /// Alert.
        /// </summary>
        [EnumMember(Value = "ALERT")]
        Alert,

        /// <summary>
        /// Ok.
        /// </summary>
        [EnumMember(Value = "OK")]
        Ok,

        /// <summary>
        /// InsufficientData.
        /// </summary>
        [EnumMember(Value = "INSUFFICIENT_DATA")]
        InsufficientData,

        /// <summary>
        /// Disabled.
        /// </summary>
        [EnumMember(Value = "DISABLED")]
        Disabled,

        /// <summary>
        /// Pending.
        /// </summary>
        [EnumMember(Value = "PENDING")]
        Pending
    }
}