// <copyright file="Type22.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Type22.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type22
    {
        /// <summary>
        /// Executable.
        /// </summary>
        [EnumMember(Value = "executable")]
        Executable,

        /// <summary>
        /// ExecutablePool.
        /// </summary>
        [EnumMember(Value = "executable_pool")]
        ExecutablePool
    }
}