// <copyright file="Type3.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// Type3.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Type3
    {
        /// <summary>
        /// Kafka.
        /// </summary>
        [EnumMember(Value = "kafka")]
        Kafka,

        /// <summary>
        /// Redpanda.
        /// </summary>
        [EnumMember(Value = "redpanda")]
        Redpanda,

        /// <summary>
        /// Msk.
        /// </summary>
        [EnumMember(Value = "msk")]
        Msk,

        /// <summary>
        /// Gcmk.
        /// </summary>
        [EnumMember(Value = "gcmk")]
        Gcmk,

        /// <summary>
        /// Confluent.
        /// </summary>
        [EnumMember(Value = "confluent")]
        Confluent,

        /// <summary>
        /// Warpstream.
        /// </summary>
        [EnumMember(Value = "warpstream")]
        Warpstream,

        /// <summary>
        /// Azureeventhub.
        /// </summary>
        [EnumMember(Value = "azureeventhub")]
        Azureeventhub,

        /// <summary>
        /// Dokafka.
        /// </summary>
        [EnumMember(Value = "dokafka")]
        Dokafka
    }
}