// <copyright file="UdfVersionCreateRequest1.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OpenApiSpecForClickHouseCloud.Standard.Models.Containers;
using OpenApiSpecForClickHouseCloud.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace OpenApiSpecForClickHouseCloud.Standard.Models
{
    /// <summary>
    /// UdfVersionCreateRequest1.
    /// </summary>
    public class UdfVersionCreateRequest1
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UdfVersionCreateRequest1"/> class.
        /// </summary>
        public UdfVersionCreateRequest1()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UdfVersionCreateRequest1"/> class.
        /// </summary>
        /// <param name="uploadId">uploadId.</param>
        /// <param name="runtime">runtime.</param>
        /// <param name="arguments">arguments.</param>
        /// <param name="returnType">returnType.</param>
        /// <param name="type">type.</param>
        /// <param name="returnName">returnName.</param>
        /// <param name="commandReadTimeout">commandReadTimeout.</param>
        /// <param name="commandWriteTimeout">commandWriteTimeout.</param>
        /// <param name="memoryLimitMib">memoryLimitMib.</param>
        /// <param name="sendChunkHeader">sendChunkHeader.</param>
        /// <param name="deterministic">deterministic.</param>
        /// <param name="format">format.</param>
        /// <param name="sandboxType">sandboxType.</param>
        /// <param name="sandboxVersion">sandboxVersion.</param>
        /// <param name="poolSize">poolSize.</param>
        /// <param name="maxCommandExecutionTime">maxCommandExecutionTime.</param>
        public UdfVersionCreateRequest1(
            Guid uploadId,
            Models.Runtime runtime,
            List<Models.UdfArgument> arguments,
            string returnType,
            string type,
            UdfVersionCreateRequest1ReturnName returnName = null,
            int? commandReadTimeout = 10000,
            int? commandWriteTimeout = 10000,
            UdfVersionCreateRequest1MemoryLimitMib memoryLimitMib = null,
            bool? sendChunkHeader = false,
            bool? deterministic = false,
            string format = "TabSeparated",
            Models.SandboxType? sandboxType = Models.SandboxType.Basic,
            Models.SandboxVersion? sandboxVersion = Models.SandboxVersion.V2,
            int? poolSize = 3,
            int? maxCommandExecutionTime = 10)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.UploadId = uploadId;
            this.Runtime = runtime;
            this.Arguments = arguments;
            this.ReturnType = returnType;
            this.ReturnName = returnName;
            this.CommandReadTimeout = commandReadTimeout;
            this.CommandWriteTimeout = commandWriteTimeout;
            this.MemoryLimitMib = memoryLimitMib;
            this.SendChunkHeader = sendChunkHeader;
            this.Deterministic = deterministic;
            this.Format = format;
            this.SandboxType = sandboxType;
            this.SandboxVersion = sandboxVersion;
            this.Type = type;
            this.PoolSize = poolSize;
            this.MaxCommandExecutionTime = maxCommandExecutionTime;
        }

        /// <summary>
        /// Identifier of the uploaded source archive.
        /// </summary>
        [JsonProperty("uploadId")]
        [JsonRequired]
        public Guid UploadId { get; set; }

        /// <summary>
        /// Gets or sets Runtime.
        /// </summary>
        [JsonProperty("runtime")]
        [JsonRequired]
        public Models.Runtime Runtime { get; set; }

        /// <summary>
        /// Gets or sets Arguments.
        /// </summary>
        [JsonProperty("arguments")]
        [JsonRequired]
        public List<Models.UdfArgument> Arguments { get; set; }

        /// <summary>
        /// Gets or sets ReturnType.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("returnType")]
        [JsonRequired]
        public string ReturnType { get; set; }

        /// <summary>
        /// Gets or sets ReturnName.
        /// </summary>
        [JsonProperty("returnName", NullValueHandling = NullValueHandling.Ignore)]
        public UdfVersionCreateRequest1ReturnName ReturnName { get; set; }

        /// <summary>
        /// Gets or sets CommandReadTimeout.
        /// </summary>
        [JsonProperty("commandReadTimeout", NullValueHandling = NullValueHandling.Ignore)]
        public int? CommandReadTimeout { get; set; }

        /// <summary>
        /// Gets or sets CommandWriteTimeout.
        /// </summary>
        [JsonProperty("commandWriteTimeout", NullValueHandling = NullValueHandling.Ignore)]
        public int? CommandWriteTimeout { get; set; }

        /// <summary>
        /// Gets or sets MemoryLimitMib.
        /// </summary>
        [JsonProperty("memoryLimitMib", NullValueHandling = NullValueHandling.Ignore)]
        public UdfVersionCreateRequest1MemoryLimitMib MemoryLimitMib { get; set; }

        /// <summary>
        /// Gets or sets SendChunkHeader.
        /// </summary>
        [JsonProperty("sendChunkHeader", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SendChunkHeader { get; set; }

        /// <summary>
        /// Marks the UDF as deterministic so ClickHouse can reuse cached query results. Only set this when the UDF always returns the same result for the same arguments.
        /// </summary>
        [JsonProperty("deterministic", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Deterministic { get; set; }

        /// <summary>
        /// Gets or sets Format.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("format", NullValueHandling = NullValueHandling.Ignore)]
        public string Format { get; set; }

        /// <summary>
        /// Gets or sets SandboxType.
        /// </summary>
        [JsonProperty("sandboxType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SandboxType? SandboxType { get; set; }

        /// <summary>
        /// Gets or sets SandboxVersion.
        /// </summary>
        [JsonProperty("sandboxVersion", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SandboxVersion? SandboxVersion { get; set; }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter), true)]
        [JsonProperty("type")]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets PoolSize.
        /// </summary>
        [JsonProperty("poolSize", NullValueHandling = NullValueHandling.Ignore)]
        public int? PoolSize { get; set; }

        /// <summary>
        /// Gets or sets MaxCommandExecutionTime.
        /// </summary>
        [JsonProperty("maxCommandExecutionTime", NullValueHandling = NullValueHandling.Ignore)]
        public int? MaxCommandExecutionTime { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UdfVersionCreateRequest1 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"UploadId = {this.UploadId}");
            toStringOutput.Add($"Runtime = {this.Runtime}");
            toStringOutput.Add($"Arguments = {(this.Arguments == null ? "null" : $"[{string.Join(", ", this.Arguments)} ]")}");
            toStringOutput.Add($"ReturnType = {this.ReturnType ?? "null"}");
            toStringOutput.Add($"ReturnName = {(this.ReturnName == null ? "null" : this.ReturnName.ToString())}");
            toStringOutput.Add($"CommandReadTimeout = {(this.CommandReadTimeout == null ? "null" : this.CommandReadTimeout.ToString())}");
            toStringOutput.Add($"CommandWriteTimeout = {(this.CommandWriteTimeout == null ? "null" : this.CommandWriteTimeout.ToString())}");
            toStringOutput.Add($"MemoryLimitMib = {(this.MemoryLimitMib == null ? "null" : this.MemoryLimitMib.ToString())}");
            toStringOutput.Add($"SendChunkHeader = {(this.SendChunkHeader == null ? "null" : this.SendChunkHeader.ToString())}");
            toStringOutput.Add($"Deterministic = {(this.Deterministic == null ? "null" : this.Deterministic.ToString())}");
            toStringOutput.Add($"Format = {this.Format ?? "null"}");
            toStringOutput.Add($"SandboxType = {(this.SandboxType == null ? "null" : this.SandboxType.ToString())}");
            toStringOutput.Add($"SandboxVersion = {(this.SandboxVersion == null ? "null" : this.SandboxVersion.ToString())}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"PoolSize = {(this.PoolSize == null ? "null" : this.PoolSize.ToString())}");
            toStringOutput.Add($"MaxCommandExecutionTime = {(this.MaxCommandExecutionTime == null ? "null" : this.MaxCommandExecutionTime.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}