// <copyright file="V1OrganizationsUdfsAttachmentsServiceId400ErrorException.cs" company="APIMatic">
// OpenApiSpecForClickHouseCloud.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using OpenApiSpecForClickHouseCloud.Standard.Http.Client;
using System;
using System.Collections.Generic;

namespace OpenApiSpecForClickHouseCloud.Standard.Exceptions
{
    /// <summary>
    /// V1OrganizationsUdfsAttachmentsServiceId400ErrorException.
    /// </summary>
    public class V1OrganizationsUdfsAttachmentsServiceId400ErrorException : ApiException
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1OrganizationsUdfsAttachmentsServiceId400ErrorException"/> class.
        /// </summary>
        /// <param name="reason"> The reason for throwing exception.</param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects.</param>
        public V1OrganizationsUdfsAttachmentsServiceId400ErrorException(string reason, HttpContext context)
            : base(reason, context)
        {
        }

        /// <summary>
        /// Human-readable error message.
        /// </summary>
        [JsonProperty("error")]
        public string Error { get; set; }

        /// <summary>
        /// HTTP status code.
        /// </summary>
        [JsonProperty("status")]
        public int Status { get; set; }

        /// <summary>
        /// Unique id assigned to every request. UUIDv4
        /// </summary>
        [JsonProperty("requestId")]
        public Guid RequestId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"V1OrganizationsUdfsAttachmentsServiceId400ErrorException : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected new void ToString(List<string> toStringOutput)
        {
            base.ToString(toStringOutput);
            toStringOutput.Add($"Error = {this.Error ?? "null"}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"RequestId = {this.RequestId}");
            toStringOutput.Add($"StackTrace = {(StackTrace != null ? $"\n{StackTrace}" : "null")}");
        }
    }
}